### ISSUE TITLE
sandbox最新版本1.2.0，安装报异常 java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by goody9807** [alibaba/jvm-sandbox#137]
java.lang.NoClassDefFoundError: com/sun/tools/attach/VirtualMachine
	at com.alibaba.jvm.sandbox.core.CoreLauncher.attachAgent(CoreLauncher.java:59)
	at com.alibaba.jvm.sandbox.core.CoreLauncher.<init>(CoreLauncher.java:20)
	at com.alibaba.jvm.sandbox.core.CoreLauncher.main(CoreLauncher.java:43)
Caused by: java.lang.ClassNotFoundException: com.sun.tools.attach.VirtualMachine
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 3 more
sandbox load jvm failed : com.sun.tools.attach.VirtualMachine
attach JVM 219695 fail.

**Comment by dongchenxu** [comment]
你用的是JRE，要用JDK
