### ISSUE TITLE
Attach Jvm失败

### ISSUE THREAD

**Issue by elseifer** [alibaba/jvm-sandbox#153]
执行 ./sandbox.sh -p 124900 报错：
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.alibaba.jvm.sandbox.core.CoreLauncher.attachAgent(CoreLauncher.java:75)
	at com.alibaba.jvm.sandbox.core.CoreLauncher.<init>(CoreLauncher.java:20)
	at com.alibaba.jvm.sandbox.core.CoreLauncher.main(CoreLauncher.java:44)
Caused by: com.sun.tools.attach.AttachNotSupportedException: Unable to open socket file: target process not responding or HotSpot VM not loaded
	at sun.tools.attach.LinuxVirtualMachine.<init>(LinuxVirtualMachine.java:106)
	at sun.tools.attach.LinuxAttachProvider.attachVirtualMachine(LinuxAttachProvider.java:78)
	at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:250)
	... 7 more
sandbox load jvm failed : Unable to open socket file: target process not responding or HotSpot VM not loaded
attach JVM 124900 fail.

**Comment by elseifer** [comment]
主要原因：启动目标应用的是admin帐号，启动sandbox的是root帐号
[stackoverflow](https://stackoverflow.com/questions/5769877/attachnotsupportedexception-due-to-missing-java-pid-file-in-attach-api)

**Comment by wangjuanmt** [comment]
> 主要原因：启动目标应用的是admin帐号，启动sandbox的是root帐号
> [stackoverflow](https://stackoverflow.com/questions/5769877/attachnotsupportedexception-due-to-missing-java-pid-file-in-attach-api)

请问有没有办法改变启动sandbox帐号为普通用户呢？

**Comment by wongoo** [comment]
@wangjuanmt  a solution: https://github.com/alibaba/jvm-sandbox/pull/185/files
