### ISSUE TITLE
attach 其他进程没有问题

### ISSUE THREAD

**Issue by qiujing2019** [alibaba/jvm-sandbox#197]
com.sun.tools.attach.AgentInitializationException: Agent JAR loaded but agent failed to initialize
        at sun.tools.attach.HotSpotVirtualMachine.loadAgent(HotSpotVirtualMachine.java:121)
        at com.alibaba.jvm.sandbox.core.CoreLauncher.attachAgent(CoreLauncher.java:61)
        at com.alibaba.jvm.sandbox.core.CoreLauncher.<init>(CoreLauncher.java:20)
        at com.alibaba.jvm.sandbox.core.CoreLauncher.main(CoreLauncher.java:43)
sandbox load jvm failed : Agent JAR loaded but agent failed to initialize

**Comment by wongoo** [comment]
@qiujing2019 check the stdout log of the target jvm, there is detail about the error.
