### ISSUE TITLE
在VirtualBox共享文件夹下，启动tomcat，无法attach

### ISSUE THREAD

**Issue by aozeliu** [alibaba/jvm-sandbox#230]
我在win10上和一个virtualbox的ubuntu18.04虚拟机共享了一个文件夹，该文件夹下有一些shell脚本，用于启动tomcat，然后attach sandbox。当我在虚拟机里的共享文件夹目录下执行该脚本时，会报错。（tomcat启动成功了，是可以访问的）
```java
com.sun.tools.attach.AttachNotSupportedException: Unable to open socket file: target process not responding or HotSpot VM not loaded
	at sun.tools.attach.LinuxVirtualMachine.<init>(LinuxVirtualMachine.java:106)
	at sun.tools.attach.LinuxAttachProvider.attachVirtualMachine(LinuxAttachProvider.java:63)
	at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:208)
	at com.alibaba.jvm.sandbox.core.CoreLauncher.attachAgent(CoreLauncher.java:59)
	at com.alibaba.jvm.sandbox.core.CoreLauncher.<init>(CoreLauncher.java:20)
	at com.alibaba.jvm.sandbox.core.CoreLauncher.main(CoreLauncher.java:43)
sandbox load jvm failed : Unable to open socket file: target process not responding or HotSpot VM not loaded
attach JVM 11070 fail.
```
shell脚本如下
```shell
#! /bin/bash

TOMCAT_BASE_DIR="/home/name/webrts/tomcat"
SANDBOX_BASE_DIR="/home/name/webrts/sandbox"

${TOMCAT_BASE_DIR}/bin/startup.sh
pid=$(ps -ef | grep ${TOMCAT_BASE_DIR} | grep -v grep | awk '{print $2}')
${SANDBOX_BASE_DIR}/bin/sandbox.sh -p $pid
``` 
但是不在共享文件下执行，就没问题。我对shell进行了分析。发现只要在共享文件夹下启动tomcat，就无法attch。这是是为什么呢？😂

**Comment by oldmanpushcart** [comment]
抱歉回答晚了，双十一是阿里最忙的时候。
你提供的信息不全呢，能否看下tomcat自己的日志，里面有真正失败的原因

**Comment by aozeliu** [comment]
这是catalina.out的日志输出，和正常启动多了thead dump.
```java
2019-12-06 08:56:34
Full thread dump OpenJDK 64-Bit Server VM (25.222-b10 mixed mode):

"AsyncFileHandlerWriter-746292446" #11 daemon prio=5 os_prio=0 tid=0x00007f4cb81f3800 nid=0x10b6 waiting on condition [0x00007f4ca592c000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000000eb8cf0c0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
        at java.util.concurrent.LinkedBlockingDeque.pollFirst(LinkedBlockingDeque.java:522)
        at java.util.concurrent.LinkedBlockingDeque.poll(LinkedBlockingDeque.java:684)
        at org.apache.juli.AsyncFileHandler$LoggerThread.run(AsyncFileHandler.java:160)

"Service Thread" #8 daemon prio=9 os_prio=0 tid=0x00007f4cb80cb800 nid=0x10a0 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread2" #7 daemon prio=9 os_prio=0 tid=0x00007f4cb80be000 nid=0x109e waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread1" #6 daemon prio=9 os_prio=0 tid=0x00007f4cb80bc800 nid=0x109d runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #5 daemon prio=9 os_prio=0 tid=0x00007f4cb80b9800 nid=0x109b waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" #4 daemon prio=9 os_prio=0 tid=0x00007f4cb80b8000 nid=0x109a waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" #3 daemon prio=8 os_prio=0 tid=0x00007f4cb8086000 nid=0x1090 in Object.wait() [0x00007f4ca6e2b000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x00000000eb788ed8> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
        - locked <0x00000000eb788ed8> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165)
        at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:216)

"Reference Handler" #2 daemon prio=10 os_prio=0 tid=0x00007f4cb8083800 nid=0x108e in Object.wait() [0x00007f4ca6f2c000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x00000000eb786c00> (a java.lang.ref.Reference$Lock)
        at java.lang.Object.wait(Object.java:502)
        at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
        - locked <0x00000000eb786c00> (a java.lang.ref.Reference$Lock)
        at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)

"main" #1 prio=5 os_prio=0 tid=0x00007f4cb800c000 nid=0x1084 waiting on condition [0x00007f4cc1e52000]
   java.lang.Thread.State: RUNNABLE
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        - locked <0x00000000ebb56c08> (a java.lang.Object)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.apache.tomcat.util.digester.Digester.<init>(Digester.java:155)
        at org.apache.catalina.startup.Catalina.createStartDigester(Catalina.java:280)
        at org.apache.catalina.startup.Catalina.load(Catalina.java:546)
        at org.apache.catalina.startup.Catalina.load(Catalina.java:662)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.catalina.startup.Bootstrap.load(Bootstrap.java:309)
        at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:492)

"VM Thread" os_prio=0 tid=0x00007f4cb8079800 nid=0x108a runnable

"GC task thread#0 (ParallelGC)" os_prio=0 tid=0x00007f4cb8021800 nid=0x1085 runnable

"GC task thread#1 (ParallelGC)" os_prio=0 tid=0x00007f4cb8023000 nid=0x1086 runnable

"GC task thread#2 (ParallelGC)" os_prio=0 tid=0x00007f4cb8025000 nid=0x1087 runnable

"GC task thread#3 (ParallelGC)" os_prio=0 tid=0x00007f4cb8026800 nid=0x1088 runnable

"VM Periodic Task Thread" os_prio=0 tid=0x00007f4cb80d6000 nid=0x10a1 waiting on condition

JNI global references: 5

Heap
 PSYoungGen      total 18432K, used 4186K [0x00000000eb780000, 0x00000000ecc00000, 0x0000000100000000)
  eden space 15872K, 26% used [0x00000000eb780000,0x00000000ebb96a80,0x00000000ec700000)
  from space 2560K, 0% used [0x00000000ec980000,0x00000000ec980000,0x00000000ecc00000)
  to   space 2560K, 0% used [0x00000000ec700000,0x00000000ec700000,0x00000000ec980000)
 ParOldGen       total 42496K, used 0K [0x00000000c2600000, 0x00000000c4f80000, 0x00000000eb780000)
  object space 42496K, 0% used [0x00000000c2600000,0x00000000c2600000,0x00000000c4f80000)
 Metaspace       used 4874K, capacity 5088K, committed 5248K, reserved 1056768K
  class space    used 529K, capacity 600K, committed 640K, reserved 1048576K

06-Dec-2019 08:56:35.165 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version:        Apache Tomcat/8.5.43
06-Dec-2019 08:56:35.167 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Jul 4 2019 20:53:15 UTC
06-Dec-2019 08:56:35.167 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server number:         8.5.43.0
06-Dec-2019 08:56:35.167 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
06-Dec-2019 08:56:35.167 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            5.0.0-36-generic
06-Dec-2019 08:56:35.167 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
06-Dec-2019 08:56:35.167 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/lib/jvm/java-8-openjdk-amd64/jre
06-Dec-2019 08:56:35.167 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           1.8.0_222-8u222-b10-1ubuntu1~18.04.1-b10
06-Dec-2019 08:56:35.167 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Private Build
06-Dec-2019 08:56:35.167 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /home/name/webrts/tomcat
06-Dec-2019 08:56:35.167 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /home/name/webrts/tomcat
06-Dec-2019 08:56:35.168 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/home/name/webrts/tomcat/conf/logging.properties
06-Dec-2019 08:56:35.168 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
06-Dec-2019 08:56:35.168 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
06-Dec-2019 08:56:35.168 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
06-Dec-2019 08:56:35.168 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027
06-Dec-2019 08:56:35.168 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=
06-Dec-2019 08:56:35.168 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/home/name/webrts/tomcat
06-Dec-2019 08:56:35.168 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/home/name/webrts/tomcat
06-Dec-2019 08:56:35.169 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/home/name/webrts/tomcat/temp
06-Dec-2019 08:56:35.169 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [/usr/java/packages/lib/amd64:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib]
06-Dec-2019 08:56:35.238 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-0.0.0.0-8080"]
06-Dec-2019 08:56:35.247 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
06-Dec-2019 08:56:35.258 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-nio-8009"]
06-Dec-2019 08:56:35.259 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
06-Dec-2019 08:56:35.260 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 431 ms
06-Dec-2019 08:56:35.298 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
06-Dec-2019 08:56:35.299 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.5.43
06-Dec-2019 08:56:35.314 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/home/name/webrts/tomcat/webapps/simple.war]
06-Dec-2019 08:56:35.549 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
06-Dec-2019 08:56:35.598 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/home/name/webrts/tomcat/webapps/simple.war] has finished in [283] ms
06-Dec-2019 08:56:35.600 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-0.0.0.0-8080"]
06-Dec-2019 08:56:35.607 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-8009"]
06-Dec-2019 08:56:35.609 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 348 ms
```

**Comment by oldmanpushcart** [comment]
比较奇怪，这个日志中并没有sandbox加载的痕迹，说明tomcat没有正常加载sandbox；
从你的脚本上来看，tomcat启动完成后立即加载sandbox，应该要有日志产生才对，能否再找找，在所有的日志目录中搜索sandbox关键词，看出现在什么地方？

**Comment by aozeliu** [comment]
抱歉😂，好像是权限问题。

我在网上搜索了一下博客，觉得关键原因可能在于这个错误 ： **Unable to open socket file** 
我使用正常的流程启动时，发现会在 /tmp 目录下生成一个 .java_pid的socket文件
而异常启动时，却没有生成这个文件。应该是因为这个文件没有正常生成，导致进程间无法通信，从而报错的
由于共享目录的owner是root，group是vboxsf的，下面的文件也是这样的，而执行脚本的用户是name。然后我sudo -i切换到root后，再执行，就启动成功了。socket文件也创建成功了

**Comment by aozeliu** [comment]
好像是执行tomcat的startup.sh时所在的目录对sandbox的启动有影响。
比如我这里在当前用户拥有的目录下执行startup.sh时，sandbox就会attach成功。但是如果在当前用户不是owner的共享文件夹下（owner为root）执行startup.sh时，sandbox就会attach失败。

**Comment by oldmanpushcart** [comment]
这个牵扯到具体使用环境，毕竟我没办法去配置你这样的环境，所以这里还希望你能继续深挖，并提出更好的环境兼容方案给到我们哦～
