### ISSUE TITLE
dead lock when sandbox initializing

### ISSUE THREAD

**Issue by wongoo** [alibaba/jvm-sandbox#233]
此死锁概率还是极低的，系统运行许久，今天第一次遇到。

从以下堆栈分析，jetty异步启动的线程锁住了SandboxClassLoader再请求AppClassLoader，同时代码编织线程锁住了AppClassLoader再请求SandboxClassLoader线程，从而导致死锁。

sandbox代码有部分重构过，将编织放到单独的一个线程处理，但分析一下这并不是导致死锁的原因。sandbox加载的时候jetty本身会异步线程初始化，和sanbox初始化主线程还是两个并发线程，还是可能导致死锁。

```
"qtp662590027-4232 Selector0" prio=10 tid=0x00007f4f41e03000 nid=0x7e75 waiting for monitor entry [0x00007f4f10be8000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:293)
        - waiting to lock <0x00000006e6a24640> (a sun.misc.Launcher$AppClassLoader)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:295)
        - locked <0x00000006e8f09578> (a com.alibaba.jvm.sandbox.agent.SandboxClassLoader)
        at com.alibaba.jvm.sandbox.agent.SandboxClassLoader.loadClass(SandboxClassLoader.java:75)
        - locked <0x00000006e8f09578> (a com.alibaba.jvm.sandbox.agent.SandboxClassLoader)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
        at org.eclipse.jetty.server.nio.SelectChannelConnector.newEndPoint(SelectChannelConnector.java:266)
        at org.eclipse.jetty.server.nio.SelectChannelConnector$ConnectorSelectorManager.newEndPoint(SelectChannelConnector.java:326)
        at org.eclipse.jetty.io.nio.SelectorManager$SelectSet.createEndPoint(SelectorManager.java:836)
        at org.eclipse.jetty.io.nio.SelectorManager$SelectSet.doSelect(SelectorManager.java:491)
        at org.eclipse.jetty.io.nio.SelectorManager$1.run(SelectorManager.java:285)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:599)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:534)
        at java.lang.Thread.run(Thread.java:662)


"watcher" daemon prio=10 tid=0x00007f4f415c3800 nid=0x7e7b waiting for monitor entry [0x00007f4f105b1000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at com.alibaba.jvm.sandbox.core.util.matcher.structure.ClassStructureFactory.createClassStructure(ClassStructureFactory.java:57)
        at com.alibaba.jvm.sandbox.core.manager.impl.SandboxClassFileTransformer.getClassStructure(SandboxClassFileTransformer.java:63)
        at com.alibaba.jvm.sandbox.core.manager.impl.SandboxClassFileTransformer._transform(SandboxClassFileTransformer.java:123)
        at com.alibaba.jvm.sandbox.core.manager.impl.SandboxClassFileTransformer.transform(SandboxClassFileTransformer.java:92)
        at sun.instrument.TransformerManager.transform(TransformerManager.java:169)
        at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:365)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
        at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
        - locked <0x00000006e6a24640> (a sun.misc.Launcher$AppClassLoader)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
        - locked <0x00000006e6a24640> (a sun.misc.Launcher$AppClassLoader)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:247)
        at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:95)
        at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:107)
        at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:31)
        at sun.reflect.annotation.AnnotationParser.parseSig(AnnotationParser.java:370)
        at sun.reflect.annotation.AnnotationParser.parseAnnotation(AnnotationParser.java:181)
        at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:69)
        at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:52)
        at java.lang.Class.initAnnotationsIfNecessary(Class.java:3070)
        - locked <0x00000007fd7a7f98> (a java.lang.Class for org.apache.hadoop.hbase.Coprocessor)
        at java.lang.Class.getDeclaredAnnotations(Class.java:3058)
        at com.alibaba.jvm.sandbox.core.util.matcher.structure.ClassStructureImplByJDK$1.initialValue(ClassStructureImplByJDK.java:190)
        at com.alibaba.jvm.sandbox.core.util.matcher.structure.ClassStructureImplByJDK$1.initialValue(ClassStructureImplByJDK.java:187)
        at com.alibaba.jvm.sandbox.core.util.LazyGet.get(LazyGet.java:23)
        at com.alibaba.jvm.sandbox.core.util.matcher.structure.ClassStructureImplByJDK.getAnnotationTypeClassStructures(ClassStructureImplByJDK.java:196)
        at com.alibaba.jvm.sandbox.core.util.matcher.structure.FamilyClassStructure$3.initialValue(FamilyClassStructure.java:94)
        at com.alibaba.jvm.sandbox.core.util.matcher.structure.FamilyClassStructure$3.initialValue(FamilyClassStructure.java:91)
        at com.alibaba.jvm.sandbox.core.util.LazyGet.get(LazyGet.java:23)
        at com.alibaba.jvm.sandbox.core.util.matcher.structure.FamilyClassStructure.getFamilyAnnotationTypeClassStructures(FamilyClassStructure.java:108)
        at com.alibaba.jvm.sandbox.core.util.matcher.ExtFilterMatcher.matchingClassStructure(ExtFilterMatcher.java:65)
        at com.alibaba.jvm.sandbox.core.util.matcher.ExtFilterMatcher.matching(ExtFilterMatcher.java:78)
        at com.alibaba.jvm.sandbox.core.util.matcher.GroupMatcher$Or.matching(GroupMatcher.java:30)
        at com.alibaba.jvm.sandbox.core.util.matcher.GroupMatcher$And.matching(GroupMatcher.java:52)
        at com.alibaba.jvm.sandbox.core.manager.impl.DefaultLoadedClassDataSource.find(DefaultLoadedClassDataSource.java:96)
        at com.alibaba.jvm.sandbox.core.manager.impl.DefaultLoadedClassDataSource.findForReTransform(DefaultLoadedClassDataSource.java:73)
        at com.alibaba.jvm.sandbox.core.manager.impl.DefaultModuleEventWatcher.findAndReTransform(DefaultModuleEventWatcher.java:252)
        at com.alibaba.jvm.sandbox.core.manager.impl.DefaultModuleEventWatcher.access$000(DefaultModuleEventWatcher.java:38)
        at com.alibaba.jvm.sandbox.core.manager.impl.DefaultModuleEventWatcher$2.run(DefaultModuleEventWatcher.java:237)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
        at java.lang.Thread.run(Thread.java:662)

ound one Java-level deadlock:
=============================
"watcher":
  waiting to lock monitor 0x0000000041429c58 (object 0x00000006e8f09578, a com.alibaba.jvm.sandbox.agent.SandboxClassLoader),
  which is held by "qtp662590027-4232 Selector0"
"qtp662590027-4232 Selector0":
  waiting to lock monitor 0x00000000414fb9c8 (object 0x00000006e6a24640, a sun.misc.Launcher$AppClassLoader),
  which is held by "watcher"

Java stack information for the threads listed above:
===================================================
"watcher":
        at com.alibaba.jvm.sandbox.core.util.matcher.structure.ClassStructureFactory.createClassStructure(ClassStructureFactory.java:57)
        at com.alibaba.jvm.sandbox.core.manager.impl.SandboxClassFileTransformer.getClassStructure(SandboxClassFileTransformer.java:63)
        at com.alibaba.jvm.sandbox.core.manager.impl.SandboxClassFileTransformer._transform(SandboxClassFileTransformer.java:123)
        at com.alibaba.jvm.sandbox.core.manager.impl.SandboxClassFileTransformer.transform(SandboxClassFileTransformer.java:92)
        at sun.instrument.TransformerManager.transform(TransformerManager.java:169)
        at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:365)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
        at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
        - locked <0x00000006e6a24640> (a sun.misc.Launcher$AppClassLoader)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
        - locked <0x00000006e6a24640> (a sun.misc.Launcher$AppClassLoader)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:247)
        at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:95)
        at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:107)
        at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:31)
        at sun.reflect.annotation.AnnotationParser.parseSig(AnnotationParser.java:370)
        at sun.reflect.annotation.AnnotationParser.parseAnnotation(AnnotationParser.java:181)
        at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:69)
        at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:52)
        at java.lang.Class.initAnnotationsIfNecessary(Class.java:3070)
        - locked <0x00000007fd7a7f98> (a java.lang.Class for org.apache.hadoop.hbase.Coprocessor)
        at java.lang.Class.getDeclaredAnnotations(Class.java:3058)
        at com.alibaba.jvm.sandbox.core.util.matcher.structure.ClassStructureImplByJDK$1.initialValue(ClassStructureImplByJDK.java:190)
        at com.alibaba.jvm.sandbox.core.util.matcher.structure.ClassStructureImplByJDK$1.initialValue(ClassStructureImplByJDK.java:187)
        at com.alibaba.jvm.sandbox.core.util.LazyGet.get(LazyGet.java:23)
        at com.alibaba.jvm.sandbox.core.util.matcher.structure.ClassStructureImplByJDK.getAnnotationTypeClassStructures(ClassStructureImplByJDK.java:196)
        at com.alibaba.jvm.sandbox.core.util.matcher.structure.FamilyClassStructure$3.initialValue(FamilyClassStructure.java:94)
        at com.alibaba.jvm.sandbox.core.util.matcher.structure.FamilyClassStructure$3.initialValue(FamilyClassStructure.java:91)
        at com.alibaba.jvm.sandbox.core.util.LazyGet.get(LazyGet.java:23)
        at com.alibaba.jvm.sandbox.core.util.matcher.structure.FamilyClassStructure.getFamilyAnnotationTypeClassStructures(FamilyClassStructure.java:108)
        at com.alibaba.jvm.sandbox.core.util.matcher.ExtFilterMatcher.matchingClassStructure(ExtFilterMatcher.java:65)
        at com.alibaba.jvm.sandbox.core.util.matcher.ExtFilterMatcher.matching(ExtFilterMatcher.java:78)
        at com.alibaba.jvm.sandbox.core.util.matcher.GroupMatcher$Or.matching(GroupMatcher.java:30)
        at com.alibaba.jvm.sandbox.core.util.matcher.GroupMatcher$And.matching(GroupMatcher.java:52)
        at com.alibaba.jvm.sandbox.core.manager.impl.DefaultLoadedClassDataSource.find(DefaultLoadedClassDataSource.java:96)
        at com.alibaba.jvm.sandbox.core.manager.impl.DefaultLoadedClassDataSource.findForReTransform(DefaultLoadedClassDataSource.java:73)
        at com.alibaba.jvm.sandbox.core.manager.impl.DefaultModuleEventWatcher.findAndReTransform(DefaultModuleEventWatcher.java:252)
        at com.alibaba.jvm.sandbox.core.manager.impl.DefaultModuleEventWatcher.access$000(DefaultModuleEventWatcher.java:38)
        at com.alibaba.jvm.sandbox.core.manager.impl.DefaultModuleEventWatcher$2.run(DefaultModuleEventWatcher.java:237)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
        at java.lang.Thread.run(Thread.java:662)
"qtp662590027-4232 Selector0":
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:293)
        - waiting to lock <0x00000006e6a24640> (a sun.misc.Launcher$AppClassLoader)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:295)
        - locked <0x00000006e8f09578> (a com.alibaba.jvm.sandbox.agent.SandboxClassLoader)
        at com.alibaba.jvm.sandbox.agent.SandboxClassLoader.loadClass(SandboxClassLoader.java:75)
        - locked <0x00000006e8f09578> (a com.alibaba.jvm.sandbox.agent.SandboxClassLoader)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
        at org.eclipse.jetty.server.nio.SelectChannelConnector.newEndPoint(SelectChannelConnector.java:266)
        at org.eclipse.jetty.server.nio.SelectChannelConnector$ConnectorSelectorManager.newEndPoint(SelectChannelConnector.java:326)
        at org.eclipse.jetty.io.nio.SelectorManager$SelectSet.createEndPoint(SelectorManager.java:836)
        at org.eclipse.jetty.io.nio.SelectorManager$SelectSet.doSelect(SelectorManager.java:491)
        at org.eclipse.jetty.io.nio.SelectorManager$1.run(SelectorManager.java:285)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:599)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:534)
        at java.lang.Thread.run(Thread.java:662)

Found 1 deadlock.      
```

**Comment by wongoo** [comment]
目前是改为同步执行代码编织可以解决此问题。

经分析，此问题发生在java 6的服务，java 6 AppClassLoader包含锁机制，而异步代码编织创造了死锁条件。

```java
 static class AppClassLoader extends URLClassLoader {
    public synchronized Class loadClass(String var1, boolean var2) throws ClassNotFoundException {
        // ...
    }
 }
```
