### ISSUE TITLE
Clock修复坏了的钟问题请教

### ISSUE THREAD

**Issue by JavaProgrammerLB** [alibaba/jvm-sandbox#236]
Clock修复坏了的钟问题请教；（-l命令能看到broken-clock-tinker模块；-d命令成功执行；class名[com.taobao.demo.Clock]和方法名[checkState]正确；没有成功修复钟，代码依旧报错）
（1）创建java工程clock；mvn clean package打包，java -cp clock-1.0.jar com.taobao.demo.Clock命令运行Clock类
（2）创建java工程clock-tinker；mvn clean package打包，cp clock-tinker-1.0-jar-with-dependencies.jar ~/.sandbox-module
（3）下载运行jvm-sandbox
```
wget https://ompc.oss.aliyuncs.com/jvm-sandbox/release/sandbox-stable-bin.zip
unzip sandbox-stable-bin.zip
cd sandbox/bin
./sandbox.sh -p 18177
./sandbox.sh -p 18177 -l
./sandbox.sh -p 18177 -d 'broken-clock-tinker/repairCheckState'
``` 
![image](https://user-images.githubusercontent.com/3973419/70603135-d96c9000-1c30-11ea-8adb-6ab0ab045628.png)

命令执行后，Clock类仍然抛异常，未打印出时间
![image](https://user-images.githubusercontent.com/3973419/70603047-ba6dfe00-1c30-11ea-9aa8-cbe4c688d304.png)

创建的代码保存在这里：
https://github.com/JavaProgrammerLB/jvm-sandbox-playground

**Comment by oldmanpushcart** [comment]
sandbox.log能上传一下么？从你描述的操作来看的确没看出什么毛病

**Comment by JavaProgrammerLB** [comment]
能；
[sandbox.log](https://github.com/alibaba/jvm-sandbox/files/3949648/sandbox.log)

**Comment by JavaProgrammerLB** [comment]
重新执行了-d 命令 ./sandbox.sh -p 25043 -d 'broken-clock-tinker/repairCheckState'
sandbox.log日志里看到了报错
2019-12-11 18:15:29 default WARN  http request value=/broken-clock-tinker/repairCheckState invoke module[id=broken-clock-tinker;] com.alibaba.jvm.sandbox.demo.BrokenClockTinkerModule#repairCheckState failed.
java.lang.NoSuchMethodError: com.alibaba.jvm.sandbox.api.listener.ext.EventWatchBuilder$IBuildingForBehavior.onWatch(Lcom/alibaba/jvm/sandbox/api/listener/ext/AdviceListener;)Lcom/alibaba/jvm/sandbox/api/listener/ext/EventWatcher;
	at com.alibaba.jvm.sandbox.demo.BrokenClockTinkerModule.repairCheckState(BrokenClockTinkerModule.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.alibaba.jvm.sandbox.core.server.jetty.servlet.ModuleHttpServlet.doMethod(ModuleHttpServlet.java:126)
	at com.alibaba.jvm.sandbox.core.server.jetty.servlet.ModuleHttpServlet.doGet(ModuleHttpServlet.java:52)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:770)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:594)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:486)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1065)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:413)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:999)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111)
	at org.eclipse.jetty.server.Server.handle(Server.java:351)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:454)
	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:890)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:944)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:634)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:230)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:77)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:609)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:45)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:599)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:534)
	at java.lang.Thread.run(Thread.java:745)
2019-12-11 18:15:29 default WARN  /sandbox/default/module/http/broken-clock-tinker/repairCheckState
java.lang.NoSuchMethodError: com.alibaba.jvm.sandbox.api.listener.ext.EventWatchBuilder$IBuildingForBehavior.onWatch(Lcom/alibaba/jvm/sandbox/api/listener/ext/AdviceListener;)Lcom/alibaba/jvm/sandbox/api/listener/ext/EventWatcher;
	at com.alibaba.jvm.sandbox.demo.BrokenClockTinkerModule.repairCheckState(BrokenClockTinkerModule.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.alibaba.jvm.sandbox.core.server.jetty.servlet.ModuleHttpServlet.doMethod(ModuleHttpServlet.java:126)
	at com.alibaba.jvm.sandbox.core.server.jetty.servlet.ModuleHttpServlet.doGet(ModuleHttpServlet.java:52)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:770)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:594)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:486)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1065)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:413)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:999)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111)
	at org.eclipse.jetty.server.Server.handle(Server.java:351)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:454)
	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:890)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:944)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:634)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:230)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:77)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:609)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:45)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:599)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:534)
	at java.lang.Thread.run(Thread.java:745)

**Comment by oldmanpushcart** [comment]
抱歉，这个是`sandbox-api-1.2.0`版本之后，修改了`EventWatchBuilder$IBuildingForBehavior#onWatch(AdviceListener adviceListener)`，没有考虑好向下兼容，给你带来了困惑。

我稍微调整了下你的代码，从AdviceListener切换到EventListener去规避这个兼容性问题。同时我会在1.3.0的版本发布中修复这个问题。

**Comment by JavaProgrammerLB** [comment]
嗯嗯，修改后Clock能成功报时
![image](https://user-images.githubusercontent.com/3973419/70681411-3cfcc900-1cd6-11ea-8ea1-9b4313396d45.png)
