### ISSUE TITLE
RoutingURLClassLoader 潜在的死锁风险

### ISSUE THREAD

**Issue by z529192557** [alibaba/jvm-sandbox#289]
内部应用上报死锁

Found one Java-level deadlock:

"shutdown-jvm-sandbox-mkagent-hook":
  waiting to lock monitor 0x00007fbf35347e78 (object 0x000000075192ebc0, a com.alibaba.jvm.sandbox.core.classloader.ModuleJarClassLoader),
  which is held by "jvm-http-connection-6"
"jvm-http-connection-6":
  waiting to lock monitor 0x00007fbec0a748e8 (object 0x000000078cfc1d08, a java.lang.Object),
  which is held by "HSFBizProcessor-DEFAULT-8-thread-7"
"HSFBizProcessor-DEFAULT-8-thread-7":
  waiting to lock monitor 0x00007fbf35347e78 (object 0x000000075192ebc0, a com.alibaba.jvm.sandbox.core.classloader.ModuleJarClassLoader),
  which is held by "jvm-http-connection-6"

Java stack information for the threads listed above:

"shutdown-jvm-sandbox-mkagent-hook":
	at java.lang.ClassLoader.loadClass(ClassLoader.java:428)
	- waiting to lock <0x000000075192ebc0> (a com.alibaba.jvm.sandbox.core.classloader.ModuleJarClassLoader)
	at com.alibaba.jvm.sandbox.core.classloader.RoutingURLClassLoader.access$601(RoutingURLClassLoader.java:20)
	at com.alibaba.jvm.sandbox.core.classloader.RoutingURLClassLoader$1.loadClass(RoutingURLClassLoader.java:95)
	at com.alibaba.jvm.sandbox.core.classloader.ClassLoadingLock.loadingInLock(ClassLoadingLock.java:55)
	- locked <0x000000072f164b50> (a java.lang.Object)
	at com.alibaba.jvm.sandbox.core.classloader.RoutingURLClassLoader.loadClass(RoutingURLClassLoader.java:62)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:435)
	- locked <0x000000072f164b60> (a java.lang.Object)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
	at com.alibaba.*.exec.plugin.mybatis.MybatisPlugin.destroy(MybatisPlugin.java:48)
	at com.alibaba.*.exec.common.aop.PluginBean.destroy(PluginBean.java:80)
	at com.alibaba.*.exec.bootstrap.jvmsandbox.SandboxModule.unloadPlugins(SandboxModule.java:131)
	at com.alibaba.*.exec.bootstrap.jvmsandbox.SandboxModule.onUnload(SandboxModule.java:96)
	at com.alibaba.jvm.sandbox.core.manager.impl.DefaultCoreModuleManager.callAndFireModuleLifeCycle(DefaultCoreModuleManager.java:106)
	at com.alibaba.jvm.sandbox.core.manager.impl.DefaultCoreModuleManager.unload(DefaultCoreModuleManager.java:361)
	- locked <0x00000007553b72e0> (a com.alibaba.jvm.sandbox.core.manager.impl.DefaultCoreModuleManager)
	at com.alibaba.jvm.sandbox.core.manager.impl.DefaultCoreModuleManager.unloadAll(DefaultCoreModuleManager.java:398)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.alibaba.jvm.sandbox.core.util.SandboxProtector$2.invoke(SandboxProtector.java:91)
	at com.sun.proxy.$Proxy147.unloadAll(Unknown Source)
	at com.alibaba.jvm.sandbox.core.JvmSandbox.destroy(JvmSandbox.java:55)
	at com.alibaba.jvm.sandbox.core.server.jetty.JettyCoreServer.destroy(JettyCoreServer.java:230)
	at com.alibaba.jvm.sandbox.core.server.ProxyCoreServer.destroy(ProxyCoreServer.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.alibaba.jvm.sandbox.agent.AgentLauncher.uninstall(AgentLauncher.java:196)
	- locked <0x0000000755f2c398> (a java.lang.Class for com.alibaba.jvm.sandbox.agent.AgentLauncher)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.commons.lang3.reflect.MethodUtils.invokeStaticMethod(MethodUtils.java:345)
	at org.apache.commons.lang3.reflect.MethodUtils.invokeStaticMethod(MethodUtils.java:308)
	at com.alibaba.jvm.sandbox.module.mgr.ControlModule.uninstall(ControlModule.java:30)
	at com.alibaba.jvm.sandbox.module.mgr.ControlModule.access$000(ControlModule.java:18)
	at com.alibaba.jvm.sandbox.module.mgr.ControlModule$1.run(ControlModule.java:48)
	at java.lang.Thread.run(Thread.java:882)
"jvm-http-connection-6":
	at com.alibaba.jvm.sandbox.core.classloader.ClassLoadingLock.loadingInLock(ClassLoadingLock.java:53)
	- waiting to lock <0x000000078cfc1d08> (a java.lang.Object)
	at com.alibaba.jvm.sandbox.core.classloader.RoutingURLClassLoader.loadClass(RoutingURLClassLoader.java:62)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
	at sun.misc.Unsafe.defineClass(Native Method)
	at sun.reflect.ClassDefiner.defineClass(ClassDefiner.java:63)
	at sun.reflect.MethodAccessorGenerator$1.run(MethodAccessorGenerator.java:399)
	at sun.reflect.MethodAccessorGenerator$1.run(MethodAccessorGenerator.java:394)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.reflect.MethodAccessorGenerator.generate(MethodAccessorGenerator.java:393)
	at sun.reflect.MethodAccessorGenerator.generateConstructor(MethodAccessorGenerator.java:92)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:55)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.createInstance(JavaBeanDeserializer.java:196)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:782)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:273)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:673)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:369)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:273)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:546)
	at com.alibaba.*.exec.common.message.http.HttpClient.execute(HttpClient.java:207)
	at com.alibaba.*.exec.common.message.http.HttpClient.postJson(HttpClient.java:157)
	at com.alibaba.*.exec.common.message.http.HttpClient$4.run(HttpClient.java:124)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:627)
	at java.lang.Thread.run(Thread.java:882)
"HSFBizProcessor-DEFAULT-8-thread-7":
	at java.lang.ClassLoader.loadClass(ClassLoader.java:428)
	- waiting to lock <0x000000075192ebc0> (a com.alibaba.jvm.sandbox.core.classloader.ModuleJarClassLoader)
	at com.alibaba.jvm.sandbox.core.classloader.RoutingURLClassLoader.access$601(RoutingURLClassLoader.java:20)
	at com.alibaba.jvm.sandbox.core.classloader.RoutingURLClassLoader$1.loadClass(RoutingURLClassLoader.java:95)
	at com.alibaba.jvm.sandbox.core.classloader.ClassLoadingLock.loadingInLock(ClassLoadingLock.java:55)
	- locked <0x000000078cfc1d08> (a java.lang.Object)
	at com.alibaba.jvm.sandbox.core.classloader.RoutingURLClassLoader.loadClass(RoutingURLClassLoader.java:62)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:435)
	- locked <0x00000007897c8498> (a java.lang.Object)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
	at com.alibaba.*.*.*.*.*.model.ClassLoaderForScript.loadClass(ClassLoaderForScript.java:44)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:435)
	- locked <0x000000077ecfed60> (a com.alibaba.*.*.*.*.*.java.JavaCodeScriptEngine$CompiledClassLoader)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
	at sun.misc.Unsafe.defineClass(Native Method)
	at sun.reflect.ClassDefiner.defineClass(ClassDefiner.java:63)
	at sun.reflect.MethodAccessorGenerator$1.run(MethodAccessorGenerator.java:399)
	at sun.reflect.MethodAccessorGenerator$1.run(MethodAccessorGenerator.java:394)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.reflect.MethodAccessorGenerator.generate(MethodAccessorGenerator.java:393)
	at sun.reflect.MethodAccessorGenerator.generateConstructor(MethodAccessorGenerator.java:92)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:55)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at com.alibaba.*.*.*.*.*.java.JavaCodeScriptEngine.execute(JavaCodeScriptEngine.java:118)
	at com.alibaba.*.*.*.*.*.base.AbstractScriptEngineService.execute(AbstractScriptEngineService.java:93)
	at com.alibaba.*.*.*.*.*.invocation.DynamicScriptInvocation.invoke(DynamicScriptInvocation.java:42)
	at com.alibaba.*.*.*.*.*.invocation.DynamicScriptInvocation.invoke(DynamicScriptInvocation.java:21)
	at com.alibaba.*.exec.plugin.hsf.consumer.HsfConsumerScriptInvocationInterceptor.invoke(HsfConsumerScriptInvocationInterceptor.java:28)
	at com.alibaba.*.exec.plugin.hsf.consumer.HsfConsumerScriptInvocationInterceptor.invoke(HsfConsumerScriptInvocationInterceptor.java:18)
	at com.alibaba.*.*.*.*.*.invocation.interceptor.RequestFilterInvocationInterceptor.invoke(RequestFilterInvocationInterceptor.java:42)
	at com.alibaba.*.*.*.*.*.invocation.interceptor.RequestFilterInvocationInterceptor.invoke(RequestFilterInvocationInterceptor.java:19)
	at com.alibaba.*.*.*.*.*.invocation.interceptor.MethodInvokeInvocationInterceptor.invoke(MethodInvokeInvocationInterceptor.java:32)
	at com.alibaba.*.*.*.*.*.invocation.interceptor.MethodInvokeInvocationInterceptor.invoke(MethodInvokeInvocationInterceptor.java:23)
	at com.alibaba.*.*.*.*.*.invocation.interceptor.InvocationParamPrepareInterceptor.invoke(InvocationParamPrepareInterceptor.java:37)
	at com.alibaba.*.*.*.*.*.invocation.interceptor.InvocationParamPrepareInterceptor.invoke(InvocationParamPrepareInterceptor.java:25)
	at com.alibaba.*.*.*.*.*.model.DynamicScriptExecutor.run(DynamicScriptExecutor.java:40)
	at com.alibaba.*.exec.common.injection.Injector.inject(Injector.java:116)
	at com.alibaba.*.exec.common.aop.BaseEnhancer.beforeAdvice(BaseEnhancer.java:38)
	at com.alibaba.*.exec.bootstrap.jvmsandbox.BeforeEventListener.handleEvent(BeforeEventListener.java:76)
	at com.alibaba.*.exec.bootstrap.jvmsandbox.BeforeEventListener.onEvent(BeforeEventListener.java:49)

**Comment by z529192557** [comment]
分析是#218 引入的加锁逻辑和1.8 原生ClassLoader.loadClass自己的逻辑 存在加锁顺序的冲突导致死锁，建议RoutingURLClassLoader修改成类似ClassLoader.loadClass的加锁方式
