### ISSUE TITLE
在时钟测试程序中遇到空指针异常

### ISSUE THREAD

**Issue by xinleigithub** [alibaba/jvm-sandbox#30]
import javax.annotation.Resource; 
    @Resource
    private ModuleEventWatcher moduleEventWatcher;
moduleEventWatcher这个对象一直获取报空指针异常，请问这个对象是如何初始化到spring中的，在spring中的id，或者如何获取。

**Comment by dongchenxu** [comment]
这个工程没有使用过spring呀~~~你抛空指针的异常堆栈能给我看下么？

**Comment by xinleigithub** [comment]
java.lang.NullPointerException: null
	at com.ccbc.combox.BrokenClockTinkerModule.repairCheckState(BrokenClockTinkerModule.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.alibaba.jvm.sandbox.core.server.jetty.servlet.ModuleHttpServlet.doMethod(ModuleHttpServlet.java:118)
	at com.alibaba.jvm.sandbox.core.server.jetty.servlet.ModuleHttpServlet.doGet(ModuleHttpServlet.java:43)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:734)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:847)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:558)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:488)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:973)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:417)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:192)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:907)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:110)
	at org.eclipse.jetty.server.Server.handle(Server.java:350)
	at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:442)
	at org.eclipse.jetty.server.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:924)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:582)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:218)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:51)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:586)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:44)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:598)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:533)
	at java.lang.Thread.run(Thread.java:745)
这全部的堆栈信息

**Comment by dongchenxu** [comment]
`BrokenClockTinkerModule.java`
你的代码给我看下

**Comment by xinleigithub** [comment]
``package com.ccbc.combox;

import javax.annotation.Resource;

import com.alibaba.jvm.sandbox.api.Information;
import com.alibaba.jvm.sandbox.api.Module;
import com.alibaba.jvm.sandbox.api.ProcessControlException;
import com.alibaba.jvm.sandbox.api.event.Event;
import com.alibaba.jvm.sandbox.api.filter.NameRegexFilter;
import com.alibaba.jvm.sandbox.api.http.Http;
import com.alibaba.jvm.sandbox.api.listener.EventListener;
import com.alibaba.jvm.sandbox.api.resource.ModuleEventWatcher;

/**
 * 修复损坏的钟模块
 */
@Information(id = "broken-clock-tinker")
public class BrokenClockTinkerModule implements Module {

    @Resource
    private ModuleEventWatcher moduleEventWatcher;

    @Http("/repairCheckState")
    public void repairCheckState() {

        moduleEventWatcher.watch(
                // 匹配到Clock$BrokenClock#checkState()
                new NameRegexFilter("TestJob", "overDueRateJob0"),

                // 监听THROWS事件并且改变原有方法抛出异常为正常返回
                new EventListener() {
                    public void onEvent(Event event) throws Throwable {

                        System.out.println("123124124124214");
                        ProcessControlException.throwReturnImmediately(null);
                    }

                },
                // 指定监听的事件为抛出异常
                Event.Type.THROWS);

    }

}

**Comment by oldmanpushcart** [comment]
亲，这个能把完整的文件贴上来么？怎么感觉你的注解不对？

**Comment by lzmhehe** [comment]
@oldmanpushcart 
这个算greys的升级版吗？ ^_^

**Comment by xinleigithub** [comment]
`package com.ccbc.combox;

import javax.annotation.Resource;

import com.alibaba.jvm.sandbox.api.Information;
import com.alibaba.jvm.sandbox.api.Module;
import com.alibaba.jvm.sandbox.api.ProcessControlException;
import com.alibaba.jvm.sandbox.api.event.Event;
import com.alibaba.jvm.sandbox.api.filter.NameRegexFilter;
import com.alibaba.jvm.sandbox.api.http.Http;
import com.alibaba.jvm.sandbox.api.listener.EventListener;
import com.alibaba.jvm.sandbox.api.resource.ModuleEventWatcher;

/**
 * 修复损坏的钟模块
 */
@Information(id = "broken-clock-tinker")
public class BrokenClockTinkerModule implements Module {

    @Resource
    private ModuleEventWatcher moduleEventWatcher;

    @Http("/repairCheckState")
    public void repairCheckState() {

        moduleEventWatcher.watch(
                // 匹配到Clock$BrokenClock#checkState()
                new NameRegexFilter("TestJob", "overDueRateJob0"),

                // 监听THROWS事件并且改变原有方法抛出异常为正常返回
                new EventListener() {
                    public void onEvent(Event event) throws Throwable {

                        System.out.println("123124124124214");
                        ProcessControlException.throwReturnImmediately(null);
                    }

                },
                // 指定监听的事件为抛出异常
                Event.Type.THROWS);

    }

}`
这是全部的时钟修复类

**Comment by oldmanpushcart** [comment]
@lzmhehe 不算～greys的核心功能是定位业务故障，JVM-SANDBOX只是一个功能容器～定位不一样。就好像你不能说淘宝是TOMCAT的升级版一样的道理～
