### ISSUE TITLE
sandbox Unable to open socket file: target process not responding or HotSpot VM not loaded

### ISSUE THREAD

**Issue by lcw521888** [alibaba/jvm-sandbox#332]
com.sun.tools.attach.AttachNotSupportedException: Unable to open socket file: target process not responding or HotSpot VM not loaded
	at sun.tools.attach.BsdVirtualMachine.<init>(BsdVirtualMachine.java:90)
	at sun.tools.attach.BsdAttachProvider.attachVirtualMachine(BsdAttachProvider.java:63)
	at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:208)
	at com.alibaba.jvm.sandbox.core.CoreLauncher.attachAgent(CoreLauncher.java:59)
	at com.alibaba.jvm.sandbox.core.CoreLauncher.<init>(CoreLauncher.java:20)
	at com.alibaba.jvm.sandbox.core.CoreLauncher.main(CoreLauncher.java:43)
sandbox load jvm failed : Unable to open socket file: target process not responding or HotSpot VM not loaded
attach JVM 19320 fail.

sandbox 用普通用户启动，执行后直接退出
请帮忙看下怎么解决

**Comment by z529192557** [comment]
目标应用程序假死或者不支持attach，检查一下目标应用程序的状态，或者控制台日志是否有报错

**Comment by shidongwa** [comment]
建议可以看看：
1，检查sandbox命令执行的用户和目标进程的用户是不是同一个
2，重启目标进程重新sandbox attach看是否成功

**Comment by kerchiner** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by code-bez** [comment]
收到

**Comment by oldmanpushcart** [comment]
咨询问题关闭
