### ISSUE TITLE
java.io.IOException: Premature EOF

### ISSUE THREAD

**Issue by yuexingliang** [alibaba/jvm-sandbox#345]
java.io.IOException: Premature EOF
	at sun.tools.attach.HotSpotVirtualMachine.readInt(HotSpotVirtualMachine.java:248)
	at sun.tools.attach.LinuxVirtualMachine.execute(LinuxVirtualMachine.java:199)
	at sun.tools.attach.HotSpotVirtualMachine.loadAgentLibrary(HotSpotVirtualMachine.java:58)
	at sun.tools.attach.HotSpotVirtualMachine.loadAgentLibrary(HotSpotVirtualMachine.java:79)
	at sun.tools.attach.HotSpotVirtualMachine.loadAgent(HotSpotVirtualMachine.java:103)
	at com.alibaba.jvm.sandbox.core.CoreLauncher.attachAgent(CoreLauncher.java:61)
	at com.alibaba.jvm.sandbox.core.CoreLauncher.<init>(CoreLauncher.java:20)
	at com.alibaba.jvm.sandbox.core.CoreLauncher.main(CoreLauncher.java:43)
sandbox load jvm failed : Premature EOF
attach JVM 93018 fail.

挂载的时候报这种错误，但是重启一下服务就可以挂载上了，这个是什么原因了？

**Comment by oldmanpushcart** [comment]
能提供下你的JDK版本信息么？我怀疑你踩到了这个bug[JDK-6882554 : Heap dump request crashs MServer](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=6882554)
