### ISSUE TITLE
attach 进程出现NoClassDefFoundError

### ISSUE THREAD

**Issue by yugonglian** [alibaba/jvm-sandbox#353]
运行命令
./sandbox.sh -p 2792

```
java.lang.NoClassDefFoundError: com/sun/tools/attach/VirtualMachine
	at com.alibaba.jvm.sandbox.core.CoreLauncher.attachAgent(CoreLauncher.java:59)
	at com.alibaba.jvm.sandbox.core.CoreLauncher.<init>(CoreLauncher.java:20)
	at com.alibaba.jvm.sandbox.core.CoreLauncher.main(CoreLauncher.java:43)
Caused by: java.lang.ClassNotFoundException: com.sun.tools.attach.VirtualMachine
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 3 more
sandbox load jvm failed : com.sun.tools.attach.VirtualMachine
attach JVM 2792 fail.
```

**Comment by code-bez** [comment]
收到

**Comment by yugonglian** [comment]
知道原因了，mac 系统dmg安装jdk 后，默认java home 是jre了，需要配置环境变量为jdk
