### ISSUE TITLE
使用sandbox attach进程后，注册的SandboxClassFileTransformer引起严重的锁竞争，影响server并发性能

### ISSUE THREAD

**Issue by aloooha** [alibaba/jvm-sandbox#364]
使用jvm-sandbox-repeater之后，发现服务接口并发严重下降，dump线程发现由SandboxClassFileTransformer引起的类加载，读取class资源引起的锁竞争。主要的线程栈如下：

"xxxExecutor-155" #2089 prio=5 os_prio=0 tid=0x00007f1f8000f800 nid=0x19dec waiting for monitor entry [0x00007f1e6d82a000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at org.apache.catalina.webresources.AbstractSingleArchiveResourceSet.getArchiveEntries(AbstractSingleArchiveResourceSet.java:66)
	- locked &lt;0x0000000782a19f68&gt; (a java.lang.Object)
	at org.apache.catalina.webresources.AbstractArchiveResourceSet.getResource(AbstractArchiveResourceSet.java:254)
	at org.apache.catalina.webresources.StandardRoot.getResourceInternal(StandardRoot.java:280)
	at org.apache.catalina.webresources.Cache.getResource(Cache.java:62)
	at org.apache.catalina.webresources.StandardRoot.getResource(StandardRoot.java:215)
	at org.apache.catalina.webresources.StandardRoot.getClassLoaderResource(StandardRoot.java:224)
	at org.apache.catalina.loader.WebappClassLoaderBase.findResource(WebappClassLoaderBase.java:928)
	at org.apache.catalina.loader.WebappClassLoaderBase.getResource(WebappClassLoaderBase.java:1049)
	at java.lang.ClassLoader.getResource(ClassLoader.java:1084)
	at java.lang.ClassLoader.getResourceAsStream(ClassLoader.java:1300)
	at com.alibaba.jvm.sandbox.core.util.matcher.structure.ClassStructureImplByAsm.getResourceAsStream(ClassStructureImplByAsm.java:280)
	at com.alibaba.jvm.sandbox.core.util.matcher.structure.ClassStructureImplByAsm.newInstance(ClassStructureImplByAsm.java:319)
	at com.alibaba.jvm.sandbox.core.util.matcher.structure.ClassStructureImplByAsm.access$100(ClassStructureImplByAsm.java:232)
	at com.alibaba.jvm.sandbox.core.util.matcher.structure.ClassStructureImplByAsm$2.initialValue(ClassStructureImplByAsm.java:378)
	at com.alibaba.jvm.sandbox.core.util.matcher.structure.ClassStructureImplByAsm$2.initialValue(ClassStructureImplByAsm.java:371)
	at com.alibaba.jvm.sandbox.api.util.LazyGet.get(LazyGet.java:25)
	at com.alibaba.jvm.sandbox.core.util.matcher.structure.ClassStructureImplByAsm.getSuperClassStructure(ClassStructureImplByAsm.java:384)
	at com.alibaba.jvm.sandbox.core.util.matcher.ExtFilterMatcher.matchingClassStructure(ExtFilterMatcher.java:62)
	at com.alibaba.jvm.sandbox.core.util.matcher.ExtFilterMatcher._matching(ExtFilterMatcher.java:111)
	at com.alibaba.jvm.sandbox.core.util.matcher.ExtFilterMatcher.matching(ExtFilterMatcher.java:78)
	at com.alibaba.jvm.sandbox.core.util.matcher.GroupMatcher$Or.matching(GroupMatcher.java:30)
	at com.alibaba.jvm.sandbox.core.util.matcher.GroupMatcher$And.matching(GroupMatcher.java:52)
	at com.alibaba.jvm.sandbox.core.manager.impl.SandboxClassFileTransformer._transform(SandboxClassFileTransformer.java:118)
	at com.alibaba.jvm.sandbox.core.manager.impl.SandboxClassFileTransformer.transform(SandboxClassFileTransformer.java:84)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at sun.misc.Unsafe.defineClass(Native Method)
	at sun.reflect.ClassDefiner.defineClass(ClassDefiner.java:63)
	at sun.reflect.MethodAccessorGenerator$1.run(MethodAccessorGenerator.java:399)
	at sun.reflect.MethodAccessorGenerator$1.run(MethodAccessorGenerator.java:394)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.reflect.MethodAccessorGenerator.generate(MethodAccessorGenerator.java:393)
	at sun.reflect.MethodAccessorGenerator.generateMethod(MethodAccessorGenerator.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:53)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.reflection.invoker.MethodInvoker.invoke(MethodInvoker.java:44)
	at org.apache.ibatis.reflection.wrapper.BeanWrapper.setBeanProperty(BeanWrapper.java:180)
	at org.apache.ibatis.reflection.wrapper.BeanWrapper.set(BeanWrapper.java:59)
	at org.apache.ibatis.reflection.MetaObject.setValue(MetaObject.java:140)

<18个等待锁0x0000000782a19f68的线程，其中一个如下：>
"xxxExecutor-180" #2135 prio=5 os_prio=0 tid=0x00007f1ef0018000 nid=0x19e2e waiting for monitor entry [0x00007f1e6b001000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at org.apache.catalina.webresources.AbstractSingleArchiveResourceSet.getArchiveEntries(AbstractSingleArchiveResourceSet.java:66)
	- waiting to lock &lt;0x0000000782a19f68&gt; (a java.lang.Object)
	at org.apache.catalina.webresources.AbstractArchiveResourceSet.getResource(AbstractArchiveResourceSet.java:254)
	at org.apache.catalina.webresources.StandardRoot.getResourceInternal(StandardRoot.java:280)
	at org.apache.catalina.webresources.Cache.getResource(Cache.java:62)
	at org.apache.catalina.webresources.StandardRoot.getResource(StandardRoot.java:215)
	at org.apache.catalina.webresources.StandardRoot.getClassLoaderResource(StandardRoot.java:224)
	at org.apache.catalina.loader.WebappClassLoaderBase.findResource(WebappClassLoaderBase.java:928)
	at org.apache.catalina.loader.WebappClassLoaderBase.getResource(WebappClassLoaderBase.java:1049)
	at java.lang.ClassLoader.getResource(ClassLoader.java:1084)
	at java.lang.ClassLoader.getResourceAsStream(ClassLoader.java:1300)
	at com.alibaba.jvm.sandbox.core.util.matcher.structure.ClassStructureImplByAsm.getResourceAsStream(ClassStructureImplByAsm.java:280)
	at com.alibaba.jvm.sandbox.core.util.matcher.structure.ClassStructureImplByAsm.newInstance(ClassStructureImplByAsm.java:319)
	at com.alibaba.jvm.sandbox.core.util.matcher.structure.ClassStructureImplByAsm.access$100(ClassStructureImplByAsm.java:232)
	at com.alibaba.jvm.sandbox.core.util.matcher.structure.ClassStructureImplByAsm$2.initialValue(ClassStructureImplByAsm.java:378)
	at com.alibaba.jvm.sandbox.core.util.matcher.structure.ClassStructureImplByAsm$2.initialValue(ClassStructureImplByAsm.java:371)
	at com.alibaba.jvm.sandbox.api.util.LazyGet.get(LazyGet.java:25)
	at com.alibaba.jvm.sandbox.core.util.matcher.structure.ClassStructureImplByAsm.getSuperClassStructure(ClassStructureImplByAsm.java:384)
	at com.alibaba.jvm.sandbox.core.util.matcher.structure.FamilyClassStructure$4.initialValue(FamilyClassStructure.java:116)
	at com.alibaba.jvm.sandbox.core.util.matcher.structure.FamilyClassStructure$4.initialValue(FamilyClassStructure.java:112)
	at com.alibaba.jvm.sandbox.api.util.LazyGet.get(LazyGet.java:25)
	at com.alibaba.jvm.sandbox.core.util.matcher.structure.FamilyClassStructure.getFamilySuperClassStructures(FamilyClassStructure.java:129)
	at com.alibaba.jvm.sandbox.core.util.matcher.structure.FamilyClassStructure$4.initialValue(FamilyClassStructure.java:121)
	at com.alibaba.jvm.sandbox.core.util.matcher.structure.FamilyClassStructure$4.initialValue(FamilyClassStructure.java:112)
	at com.alibaba.jvm.sandbox.api.util.LazyGet.get(LazyGet.java:25)
	at com.alibaba.jvm.sandbox.core.util.matcher.structure.FamilyClassStructure.getFamilySuperClassStructures(FamilyClassStructure.java:129)
	at com.alibaba.jvm.sandbox.core.util.matcher.structure.FamilyClassStructure$1.initialValue(FamilyClassStructure.java:26)
	at com.alibaba.jvm.sandbox.core.util.matcher.structure.FamilyClassStructure$1.initialValue(FamilyClassStructure.java:13)
	at com.alibaba.jvm.sandbox.api.util.LazyGet.get(LazyGet.java:25)
	at com.alibaba.jvm.sandbox.core.util.matcher.structure.FamilyClassStructure.getFamilyInterfaceClassStructures(FamilyClassStructure.java:36)
	at com.alibaba.jvm.sandbox.core.util.matcher.ExtFilterMatcher.matchingClassStructure(ExtFilterMatcher.java:65)
	at com.alibaba.jvm.sandbox.core.util.matcher.ExtFilterMatcher._matching(ExtFilterMatcher.java:111)
	at com.alibaba.jvm.sandbox.core.util.matcher.ExtFilterMatcher.matching(ExtFilterMatcher.java:78)
	at com.alibaba.jvm.sandbox.core.util.matcher.GroupMatcher$Or.matching(GroupMatcher.java:30)
	at com.alibaba.jvm.sandbox.core.util.matcher.GroupMatcher$And.matching(GroupMatcher.java:52)
	at com.alibaba.jvm.sandbox.core.manager.impl.SandboxClassFileTransformer._transform(SandboxClassFileTransformer.java:118)
	at com.alibaba.jvm.sandbox.core.manager.impl.SandboxClassFileTransformer.transform(SandboxClassFileTransformer.java:84)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at sun.misc.Unsafe.defineClass(Native Method)
	at sun.reflect.ClassDefiner.defineClass(ClassDefiner.java:63)
	at sun.reflect.MethodAccessorGenerator$1.run(MethodAccessorGenerator.java:399)
	at sun.reflect.MethodAccessorGenerator$1.run(MethodAccessorGenerator.java:394)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.reflect.MethodAccessorGenerator.generate(MethodAccessorGenerator.java:393)
	at sun.reflect.MethodAccessorGenerator.generateMethod(MethodAccessorGenerator.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:53)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.reflection.invoker.MethodInvoker.invoke(MethodInvoker.java:44)
	at org.apache.ibatis.reflection.wrapper.BeanWrapper.getBeanProperty(BeanWrapper.java:164)
	at org.apache.ibatis.reflection.wrapper.BeanWrapper.get(BeanWrapper.java:49)
	at org.apache.ibatis.reflection.MetaObject.getValue(MetaObject.java:122)

*************************************************************************************************************************************************************************
"xxxExecutor-126" #2038 prio=5 os_prio=0 tid=0x00007f1ef800d000 nid=0x19dab waiting for monitor entry [0x00007f1e71565000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at org.apache.catalina.webresources.AbstractSingleArchiveResourceSet.getArchiveEntries(AbstractSingleArchiveResourceSet.java:66)
	- locked &lt;0x000000078286d840&gt; (a java.lang.Object)
	at org.apache.catalina.webresources.AbstractArchiveResourceSet.getResource(AbstractArchiveResourceSet.java:254)
	at org.apache.catalina.webresources.StandardRoot.getResourceInternal(StandardRoot.java:280)
	at org.apache.catalina.webresources.Cache.getResource(Cache.java:62)
	at org.apache.catalina.webresources.StandardRoot.getResource(StandardRoot.java:215)
	at org.apache.catalina.webresources.StandardRoot.getClassLoaderResource(StandardRoot.java:224)
	at org.apache.catalina.loader.WebappClassLoaderBase.findResource(WebappClassLoaderBase.java:928)
	at org.apache.catalina.loader.WebappClassLoaderBase.getResource(WebappClassLoaderBase.java:1049)
	at java.lang.ClassLoader.getResource(ClassLoader.java:1084)
	at java.lang.ClassLoader.getResourceAsStream(ClassLoader.java:1300)
	at com.alibaba.jvm.sandbox.core.util.matcher.structure.ClassStructureImplByAsm.getResourceAsStream(ClassStructureImplByAsm.java:280)
	at com.alibaba.jvm.sandbox.core.util.matcher.structure.ClassStructureImplByAsm.newInstance(ClassStructureImplByAsm.java:319)
	at com.alibaba.jvm.sandbox.core.util.matcher.structure.ClassStructureImplByAsm.access$100(ClassStructureImplByAsm.java:232)
	at com.alibaba.jvm.sandbox.core.util.matcher.structure.ClassStructureImplByAsm$2.initialValue(ClassStructureImplByAsm.java:378)
	at com.alibaba.jvm.sandbox.core.util.matcher.structure.ClassStructureImplByAsm$2.initialValue(ClassStructureImplByAsm.java:371)
	at com.alibaba.jvm.sandbox.api.util.LazyGet.get(LazyGet.java:25)
	at com.alibaba.jvm.sandbox.core.util.matcher.structure.ClassStructureImplByAsm.getSuperClassStructure(ClassStructureImplByAsm.java:384)
	at com.alibaba.jvm.sandbox.core.util.matcher.ExtFilterMatcher.matchingClassStructure(ExtFilterMatcher.java:62)
	at com.alibaba.jvm.sandbox.core.util.matcher.ExtFilterMatcher._matching(ExtFilterMatcher.java:111)
	at com.alibaba.jvm.sandbox.core.util.matcher.ExtFilterMatcher.matching(ExtFilterMatcher.java:78)
	at com.alibaba.jvm.sandbox.core.util.matcher.GroupMatcher$Or.matching(GroupMatcher.java:30)
	at com.alibaba.jvm.sandbox.core.util.matcher.GroupMatcher$And.matching(GroupMatcher.java:52)
	at com.alibaba.jvm.sandbox.core.manager.impl.SandboxClassFileTransformer._transform(SandboxClassFileTransformer.java:118)
	at com.alibaba.jvm.sandbox.core.manager.impl.SandboxClassFileTransformer.transform(SandboxClassFileTransformer.java:84)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at sun.misc.Unsafe.defineClass(Native Method)
	at sun.reflect.ClassDefiner.defineClass(ClassDefiner.java:63)
	at sun.reflect.MethodAccessorGenerator$1.run(MethodAccessorGenerator.java:399)
	at sun.reflect.MethodAccessorGenerator$1.run(MethodAccessorGenerator.java:394)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.reflect.MethodAccessorGenerator.generate(MethodAccessorGenerator.java:393)
	at sun.reflect.MethodAccessorGenerator.generateMethod(MethodAccessorGenerator.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:53)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.BeanUtils.copyProperties(BeanUtils.java:729)
	at org.springframework.beans.BeanUtils.copyProperties(BeanUtils.java:649)

<46个等待锁0x0000000782a19f68的线程，其中一个如下：>
"xxxExecutor-127" #2037 prio=5 os_prio=0 tid=0x00007f2108013000 nid=0x19daa waiting for monitor entry [0x00007f1e71666000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at org.apache.catalina.webresources.AbstractSingleArchiveResourceSet.getArchiveEntries(AbstractSingleArchiveResourceSet.java:66)
	- waiting to lock &lt;0x000000078286d840&gt; (a java.lang.Object)
	at org.apache.catalina.webresources.AbstractArchiveResourceSet.getResource(AbstractArchiveResourceSet.java:254)
	at org.apache.catalina.webresources.StandardRoot.getResourceInternal(StandardRoot.java:280)
	at org.apache.catalina.webresources.Cache.getResource(Cache.java:62)
	at org.apache.catalina.webresources.StandardRoot.getResource(StandardRoot.java:215)
	at org.apache.catalina.webresources.StandardRoot.getClassLoaderResource(StandardRoot.java:224)
	at org.apache.catalina.loader.WebappClassLoaderBase.findResource(WebappClassLoaderBase.java:928)
	at org.apache.catalina.loader.WebappClassLoaderBase.getResource(WebappClassLoaderBase.java:1049)
	at java.lang.ClassLoader.getResource(ClassLoader.java:1084)
	at java.lang.ClassLoader.getResourceAsStream(ClassLoader.java:1300)
	at com.alibaba.jvm.sandbox.core.util.matcher.structure.ClassStructureImplByAsm.getResourceAsStream(ClassStructureImplByAsm.java:280)
	at com.alibaba.jvm.sandbox.core.util.matcher.structure.ClassStructureImplByAsm.newInstance(ClassStructureImplByAsm.java:319)
	at com.alibaba.jvm.sandbox.core.util.matcher.structure.ClassStructureImplByAsm.access$100(ClassStructureImplByAsm.java:232)
	at com.alibaba.jvm.sandbox.core.util.matcher.structure.ClassStructureImplByAsm$2.initialValue(ClassStructureImplByAsm.java:378)
	at com.alibaba.jvm.sandbox.core.util.matcher.structure.ClassStructureImplByAsm$2.initialValue(ClassStructureImplByAsm.java:371)
	at com.alibaba.jvm.sandbox.api.util.LazyGet.get(LazyGet.java:25)
	at com.alibaba.jvm.sandbox.core.util.matcher.structure.ClassStructureImplByAsm.getSuperClassStructure(ClassStructureImplByAsm.java:384)
	at com.alibaba.jvm.sandbox.core.util.matcher.ExtFilterMatcher.matchingClassStructure(ExtFilterMatcher.java:62)
	at com.alibaba.jvm.sandbox.core.util.matcher.ExtFilterMatcher._matching(ExtFilterMatcher.java:111)
	at com.alibaba.jvm.sandbox.core.util.matcher.ExtFilterMatcher.matching(ExtFilterMatcher.java:78)
	at com.alibaba.jvm.sandbox.core.util.matcher.GroupMatcher$Or.matching(GroupMatcher.java:30)
	at com.alibaba.jvm.sandbox.core.util.matcher.GroupMatcher$And.matching(GroupMatcher.java:52)
	at com.alibaba.jvm.sandbox.core.manager.impl.SandboxClassFileTransformer._transform(SandboxClassFileTransformer.java:118)
	at com.alibaba.jvm.sandbox.core.manager.impl.SandboxClassFileTransformer.transform(SandboxClassFileTransformer.java:84)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at sun.misc.Unsafe.defineClass(Native Method)
	at sun.reflect.ClassDefiner.defineClass(ClassDefiner.java:63)
	at sun.reflect.MethodAccessorGenerator$1.run(MethodAccessorGenerator.java:399)
	at sun.reflect.MethodAccessorGenerator$1.run(MethodAccessorGenerator.java:394)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.reflect.MethodAccessorGenerator.generate(MethodAccessorGenerator.java:393)
	at sun.reflect.MethodAccessorGenerator.generateMethod(MethodAccessorGenerator.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:53)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.reflection.invoker.MethodInvoker.invoke(MethodInvoker.java:44)
	at org.apache.ibatis.reflection.wrapper.BeanWrapper.getBeanProperty(BeanWrapper.java:164)
	at org.apache.ibatis.reflection.wrapper.BeanWrapper.get(BeanWrapper.java:49)
	at org.apache.ibatis.reflection.MetaObject.getValue(MetaObject.java:122)

*****************************************************************************************************************************
"xxxExecutor-126" #2038 prio=5 os_prio=0 tid=0x00007f1ef800d000 nid=0x19dab waiting for monitor entry [0x00007f1e71565000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at org.apache.catalina.webresources.AbstractSingleArchiveResourceSet.getArchiveEntries(AbstractSingleArchiveResourceSet.java:66)
	- locked &lt;0x000000078286d840&gt; (a java.lang.Object)
	at org.apache.catalina.webresources.AbstractArchiveResourceSet.getResource(AbstractArchiveResourceSet.java:254)
	at org.apache.catalina.webresources.StandardRoot.getResourceInternal(StandardRoot.java:280)
	at org.apache.catalina.webresources.Cache.getResource(Cache.java:62)
	at org.apache.catalina.webresources.StandardRoot.getResource(StandardRoot.java:215)
	at org.apache.catalina.webresources.StandardRoot.getClassLoaderResource(StandardRoot.java:224)
	at org.apache.catalina.loader.WebappClassLoaderBase.findResource(WebappClassLoaderBase.java:928)
	at org.apache.catalina.loader.WebappClassLoaderBase.getResource(WebappClassLoaderBase.java:1049)
	at java.lang.ClassLoader.getResource(ClassLoader.java:1084)
	at java.lang.ClassLoader.getResourceAsStream(ClassLoader.java:1300)
	at com.alibaba.jvm.sandbox.core.util.matcher.structure.ClassStructureImplByAsm.getResourceAsStream(ClassStructureImplByAsm.java:280)
	at com.alibaba.jvm.sandbox.core.util.matcher.structure.ClassStructureImplByAsm.newInstance(ClassStructureImplByAsm.java:319)
	at com.alibaba.jvm.sandbox.core.util.matcher.structure.ClassStructureImplByAsm.access$100(ClassStructureImplByAsm.java:232)
	at com.alibaba.jvm.sandbox.core.util.matcher.structure.ClassStructureImplByAsm$2.initialValue(ClassStructureImplByAsm.java:378)
	at com.alibaba.jvm.sandbox.core.util.matcher.structure.ClassStructureImplByAsm$2.initialValue(ClassStructureImplByAsm.java:371)
	at com.alibaba.jvm.sandbox.api.util.LazyGet.get(LazyGet.java:25)
	at com.alibaba.jvm.sandbox.core.util.matcher.structure.ClassStructureImplByAsm.getSuperClassStructure(ClassStructureImplByAsm.java:384)
	at com.alibaba.jvm.sandbox.core.util.matcher.ExtFilterMatcher.matchingClassStructure(ExtFilterMatcher.java:62)
	at com.alibaba.jvm.sandbox.core.util.matcher.ExtFilterMatcher._matching(ExtFilterMatcher.java:111)
	at com.alibaba.jvm.sandbox.core.util.matcher.ExtFilterMatcher.matching(ExtFilterMatcher.java:78)
	at com.alibaba.jvm.sandbox.core.util.matcher.GroupMatcher$Or.matching(GroupMatcher.java:30)
	at com.alibaba.jvm.sandbox.core.util.matcher.GroupMatcher$And.matching(GroupMatcher.java:52)
	at com.alibaba.jvm.sandbox.core.manager.impl.SandboxClassFileTransformer._transform(SandboxClassFileTransformer.java:118)
	at com.alibaba.jvm.sandbox.core.manager.impl.SandboxClassFileTransformer.transform(SandboxClassFileTransformer.java:84)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at sun.misc.Unsafe.defineClass(Native Method)
	at sun.reflect.ClassDefiner.defineClass(ClassDefiner.java:63)
	at sun.reflect.MethodAccessorGenerator$1.run(MethodAccessorGenerator.java:399)
	at sun.reflect.MethodAccessorGenerator$1.run(MethodAccessorGenerator.java:394)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.reflect.MethodAccessorGenerator.generate(MethodAccessorGenerator.java:393)
	at sun.reflect.MethodAccessorGenerator.generateMethod(MethodAccessorGenerator.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:53)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.BeanUtils.copyProperties(BeanUtils.java:729)
	at org.springframework.beans.BeanUtils.copyProperties(BeanUtils.java:649)

<56个等待锁0x0000000782a19f68的线程，其中一个如下：>
"xxxExecutor-130" #2034 prio=5 os_prio=0 tid=0x00007f22c0070800 nid=0x19da6 waiting for monitor entry [0x00007f1e71a6a000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at org.apache.catalina.webresources.AbstractSingleArchiveResourceSet.getArchiveEntries(AbstractSingleArchiveResourceSet.java:66)
	- waiting to lock &lt;0x000000078286d840&gt; (a java.lang.Object)
	at org.apache.catalina.webresources.AbstractArchiveResourceSet.getResource(AbstractArchiveResourceSet.java:254)
	at org.apache.catalina.webresources.StandardRoot.getResourceInternal(StandardRoot.java:280)
	at org.apache.catalina.webresources.Cache.getResource(Cache.java:62)
	at org.apache.catalina.webresources.StandardRoot.getResource(StandardRoot.java:215)
	at org.apache.catalina.webresources.StandardRoot.getClassLoaderResource(StandardRoot.java:224)
	at org.apache.catalina.loader.WebappClassLoaderBase.findResource(WebappClassLoaderBase.java:928)
	at org.apache.catalina.loader.WebappClassLoaderBase.getResource(WebappClassLoaderBase.java:1049)
	at java.lang.ClassLoader.getResource(ClassLoader.java:1084)
	at java.lang.ClassLoader.getResourceAsStream(ClassLoader.java:1300)
	at com.alibaba.jvm.sandbox.core.util.matcher.structure.ClassStructureImplByAsm.getResourceAsStream(ClassStructureImplByAsm.java:280)
	at com.alibaba.jvm.sandbox.core.util.matcher.structure.ClassStructureImplByAsm.newInstance(ClassStructureImplByAsm.java:319)
	at com.alibaba.jvm.sandbox.core.util.matcher.structure.ClassStructureImplByAsm.newInstances(ClassStructureImplByAsm.java:347)
	at com.alibaba.jvm.sandbox.core.util.matcher.structure.ClassStructureImplByAsm.access$200(ClassStructureImplByAsm.java:232)
	at com.alibaba.jvm.sandbox.core.util.matcher.structure.ClassStructureImplByAsm$3.initialValue(ClassStructureImplByAsm.java:391)
	at com.alibaba.jvm.sandbox.core.util.matcher.structure.ClassStructureImplByAsm$3.initialValue(ClassStructureImplByAsm.java:388)
	at com.alibaba.jvm.sandbox.api.util.LazyGet.get(LazyGet.java:25)
	at com.alibaba.jvm.sandbox.core.util.matcher.structure.ClassStructureImplByAsm.getInterfaceClassStructures(ClassStructureImplByAsm.java:397)
	at com.alibaba.jvm.sandbox.core.util.matcher.structure.FamilyClassStructure$1.initialValue(FamilyClassStructure.java:17)
	at com.alibaba.jvm.sandbox.core.util.matcher.structure.FamilyClassStructure$1.initialValue(FamilyClassStructure.java:13)
	at com.alibaba.jvm.sandbox.api.util.LazyGet.get(LazyGet.java:25)
	at com.alibaba.jvm.sandbox.core.util.matcher.structure.FamilyClassStructure.getFamilyInterfaceClassStructures(FamilyClassStructure.java:36)
	at com.alibaba.jvm.sandbox.core.util.matcher.structure.FamilyClassStructure$1.initialValue(FamilyClassStructure.java:27)
	at com.alibaba.jvm.sandbox.core.util.matcher.structure.FamilyClassStructure$1.initialValue(FamilyClassStructure.java:13)
	at com.alibaba.jvm.sandbox.api.util.LazyGet.get(LazyGet.java:25)
	at com.alibaba.jvm.sandbox.core.util.matcher.structure.FamilyClassStructure.getFamilyInterfaceClassStructures(FamilyClassStructure.java:36)
	at com.alibaba.jvm.sandbox.core.util.matcher.ExtFilterMatcher.matchingClassStructure(ExtFilterMatcher.java:65)
	at com.alibaba.jvm.sandbox.core.util.matcher.ExtFilterMatcher._matching(ExtFilterMatcher.java:111)
	at com.alibaba.jvm.sandbox.core.util.matcher.ExtFilterMatcher.matching(ExtFilterMatcher.java:78)
	at com.alibaba.jvm.sandbox.core.util.matcher.GroupMatcher$Or.matching(GroupMatcher.java:30)
	at com.alibaba.jvm.sandbox.core.util.matcher.GroupMatcher$And.matching(GroupMatcher.java:52)
	at com.alibaba.jvm.sandbox.core.manager.impl.SandboxClassFileTransformer._transform(SandboxClassFileTransformer.java:118)
	at com.alibaba.jvm.sandbox.core.manager.impl.SandboxClassFileTransformer.transform(SandboxClassFileTransformer.java:84)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at sun.misc.Unsafe.defineClass(Native Method)
	at sun.reflect.ClassDefiner.defineClass(ClassDefiner.java:63)
	at sun.reflect.MethodAccessorGenerator$1.run(MethodAccessorGenerator.java:399)
	at sun.reflect.MethodAccessorGenerator$1.run(MethodAccessorGenerator.java:394)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.reflect.MethodAccessorGenerator.generate(MethodAccessorGenerator.java:393)
	at sun.reflect.MethodAccessorGenerator.generateMethod(MethodAccessorGenerator.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:53)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:141)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:313)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:176)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3629)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3597)
	at com.aloha.utils.JsonUtils.unMarshal(JsonUtils.java:50)
	at com.aloha.utils.JSON.parseObject(JSON.java:200)

**Comment by z529192557** [comment]
tomcat版本提供一下

**Comment by oldmanpushcart** [comment]
升级到1.4.0，优化了match的逻辑，降低了竞争
