### ISSUE TITLE
监听业务代码，-d报错ClassNotFoundException

### ISSUE THREAD

**Issue by songjinze** [alibaba/jvm-sandbox#390]
```
@MetaInfServices(Module.class)
@Information(id = "trigger_info_spy")
public class TriggerInfoSpy implements Module {

    @Resource
    private ModuleEventWatcher watcher;

    @Command("start_record_trigger_info")
    public void startRecordTriggerInfo(final Map<String, String> param) {
        new EventWatchBuilder(watcher)
                .onClass("xxx")
                .includeSubClasses()
                .onBehavior("xxx")
                .onWatch(new TriggerInfoAnalysisAdviceListener());
    }
}

```
在TriggerInfoAnalysisAdviceListener中的方法里会引用到大量业务类，所以所有import都放在这个listener里了。但是看起来，使用sandbox -d的时候还是会有类找不到的问题。
```
2022-10-20 15:31:20 default WARN  /sandbox/default/module/http/trigger_info_spy/start_record_trigger_info
java.lang.NoClassDefFoundError: xxx/xxx
	at xxx.startRecordTriggerInfo(TriggerInfoSpy.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.alibaba.jvm.sandbox.core.server.jetty.servlet.ModuleHttpServlet.doMethod(ModuleHttpServlet.java:133)
	at com.alibaba.jvm.sandbox.core.server.jetty.servlet.ModuleHttpServlet.doGet(ModuleHttpServlet.java:54)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:770)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:594)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:486)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1065)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:413)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:999)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111)
	at org.eclipse.jetty.server.Server.handle(Server.java:351)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:454)
	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:890)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:944)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:634)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:230)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:77)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:609)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:45)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:599)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:534)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.ClassNotFoundException: xxx.xxx
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at com.alibaba.jvm.sandbox.core.classloader.RoutingURLClassLoader.access$601(RoutingURLClassLoader.java:22)
	at com.alibaba.jvm.sandbox.core.classloader.RoutingURLClassLoader$1.loadClass(RoutingURLClassLoader.java:105)
	at com.alibaba.jvm.sandbox.core.classloader.ClassLoadingLock.loadingInLock(ClassLoadingLock.java:55)
	at com.alibaba.jvm.sandbox.core.classloader.RoutingURLClassLoader.loadClass(RoutingURLClassLoader.java:64)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 28 common frames omitted
```
业务工程中对应的类可以运行，没有做额外的配置，项目是用tomcat启动的，sandbox看起来找不到，请问是什么原因？

**Comment by songjinze** [comment]
maven配置直接用的parent
```
<parent>
        <groupId>com.alibaba.jvm.sandbox</groupId>
        <artifactId>sandbox-module-starter</artifactId>
        <version>1.3.1</version>
    </parent>
```

**Comment by songjinze** [comment]
另外问一下，如果attach的jvm中类没有加载的情况下（还未使用），sandbox可以正确拦截吗，因为这个bug不是所有Module都出现，一些import了业务类的module是没有出现的。

**Comment by oldmanpushcart** [comment]
将业务类打包到module中是不行的，因为Module是独立的ClassLoader进行加载，与业务代码的ClassLoader隔离。这里你必须要用反射来掉用。

**Comment by songjinze** [comment]
感谢，我get到了，只能在listener的具体方法执行时加载，这时当前线程的classLoader才是业务上的classLoader。
