### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/catalina/connector/Response

### ISSUE THREAD

**Issue by yihengwang4** [alibaba/jvm-sandbox#404]
您好，想请教个问题，部分类在after()里面会报java.lang.NoClassDefFoundError，但是在before()里面就不会报这个错误。而且如果在before里面使用（加载）了这个类，在after()里面也不会报这个错误了。

**Comment by oldmanpushcart** [comment]
能给出`java.lang.NoClassDefFoundError`具体的堆栈么？从逻辑上并应该会出现此类问题，我需要堆栈信息作更详细的判断。

**Comment by yihengwang4** [comment]
如果应用用idea启动就不会有这个问题，命令行启动就会有这个错误，具体堆栈信息如下，十分感谢

`java.lang.NoClassDefFoundError: org/apache/catalina/connector/Response
	at com.alibaba.jvm.sandbox.module.replay.plugin.HookTomcat.sendNew(HookTomcat.java:203)
	at com.alibaba.jvm.sandbox.module.replay.plugin.Hook$1.afterIntercepter(Hook.java:190)
	at com.alibaba.jvm.sandbox.module.replay.plugin.Hook$1.afterReturning(Hook.java:150)
	at com.alibaba.jvm.sandbox.api.listener.ext.AdviceAdapterListener.switchEvent(AdviceAdapterListener.java:118)
	at com.alibaba.jvm.sandbox.api.listener.ext.AdviceAdapterListener.onEvent(AdviceAdapterListener.java:39)
	at com.alibaba.jvm.sandbox.core.enhance.weaver.EventListenerHandler.handleEvent(EventListenerHandler.java:117)
	at com.alibaba.jvm.sandbox.core.enhance.weaver.EventListenerHandler.handleOnEnd(EventListenerHandler.java:441)
	at com.alibaba.jvm.sandbox.core.enhance.weaver.EventListenerHandler.handleOnReturn(EventListenerHandler.java:371)
	at java.com.alibaba.jvm.sandbox.spy.Spy.spyMethodOnReturn(Spy.java:192)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:75)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:860)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1589)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.apache.catalina.connector.Response
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at com.alibaba.jvm.sandbox.core.classloader.RoutingURLClassLoader.access$601(RoutingURLClassLoader.java:21)
	at com.alibaba.jvm.sandbox.core.classloader.RoutingURLClassLoader$1.loadClass(RoutingURLClassLoader.java:104)
	at com.alibaba.jvm.sandbox.core.classloader.ClassLoadingLock.loadingInLock(ClassLoadingLock.java:55)
	at com.alibaba.jvm.sandbox.core.classloader.RoutingURLClassLoader.loadClass(RoutingURLClassLoader.java:63)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 20 common frames omitted
`

**Comment by yihengwang4** [comment]
此外在HttpServlet的service()处做增强并将入参转换为HttpServletRequest时，会出现错误：java.lang.ClassCastException: org.apache.catalina.connector.RequestFacade cannot be cast to javax.servlet.http.HttpServletRequest。
打印如下日志：
`log.info("classLoader1 = {}, classLoader2 = {}, currentClassLoader = {}",
                allArguments[0].getClass().getClassLoader().getClass().getName(),
                HttpServletRequest.class.getClassLoader().getClass().getName(),
                Thread.currentThread().getContextClassLoader().getClass().getName());`
结果为：
`classLoader1 = org.springframework.boot.loader.LaunchedURLClassLoader, classLoader2 = com.alibaba.jvm.sandbox.agent.SandboxClassLoader, currentClassLoader = org.springframework.boot.web.embedded.tomcat.TomcatEmbeddedWebappClassLoader`

**Comment by oldmanpushcart** [comment]
明白了，从堆栈来看，这个应该是另一个开源项目[jvm-sandbox-repeater](https://github.com/alibaba/jvm-sandbox-repeater)的问题，我没研究过这个项目的代码。

建议你移到那个项目询问，嘿嘿

**Comment by yihengwang4** [comment]
这个是一个demo项目，当时package命名的时候随便取的，和jvm-sandbox-repeater有点类似，但和该项目无关

**Comment by oldmanpushcart** [comment]
哦，看到你更新的代码了，`javax.servlet.http.HttpServletRequest`这个类是直接被SandboxClassLoader所加载的。
```java
private ModuleJarClassLoader(final File moduleJarFile,
                                 final File tempModuleJarFile,
                                 final Routing... specialRouting) throws IOException {
      super(
              new URL[]{new URL("file:" + tempModuleJarFile.getPath())},
              assembleRouting(new Routing(
                      ModuleJarClassLoader.class.getClassLoader(),
                      "^com\\.alibaba\\.jvm\\.sandbox\\.api\\..*$",
                      "^javax\\.servlet\\..*$",
                      "^javax\\.annotation\\.Resource.*$"
              ), specialRouting)
      );
      // ...
  }
```

我的建议是用反射来操作这个包下的类，具体可以参考debug模块的`DebugLogServletAccessModule`

**Comment by yihengwang4** [comment]
哦哦好的，谢谢～那java.lang.NoClassDefFoundError这个问题是为什么捏

**Comment by yihengwang4** [comment]
能再请教下SandboxClassLoader直接还在javax.servlet.*的目的是啥吗？

**Comment by oldmanpushcart** [comment]
`java.lang.NoClassDefFoundError`是Java虚拟机在编译时能找到合适的类,而在运行时不能找到合适的类导致的错误。

初步的怀疑是你在写Module的时候是依赖了Tomcat的包，但实际Module在打包的时候没有把这个类打包进来。至于打包进来能不能解决问题，那要看HookTomcat.java是怎么用这个类的了。

我从堆栈的方法名上猜测你大概的代码，估计就算引进来了，你也会出现`java.lang.ClassCastException`，不过猜测是不好的习惯还是直接用反射来操作你的类吧。

**Comment by yihengwang4** [comment]
使用了`<scope>provided</scope>`，确实没有将tomcat的包打进来，但是`java.lang.NoClassDefFoundError`只出现在增强点执行后，增强点执行前就不会出现这个错误

**Comment by XuelinHu** [comment]
> org.apache.catalina.connector.RequestFacade cannot be cast to javax.servlet.http.HttpServletRequest。

这个问题有遇到过类似的，

org.apache.catalina.connector.RequestFacade 的类加载器可能是**org.springframework.boot.loader.LaunchedURLClassLoader**，
 javax.servlet.http.HttpServletRequest 的类加载器可能是**com.alibaba.jvm.sandbox.agent.SandboxClassLoader**的，
虽然
`public class RequestFacade implements HttpServletRequest`
但两个类现在是不同的类加载器，是不能强转。
###  可以参考的解决方法有：
jvm-sandbox-repeater的http增强就是把Http相关的类，使用**org.springframework.boot.loader.LaunchedURLClassLoader**来加载，具体作法是重写了类加载器，[jvm-sandbox-repeater PluginClassLoader 类源码地址](https://github.com/alibaba/jvm-sandbox-repeater/blob/0a1b47b2aae295a5c4627e533e7da94b9ed2b14d/repeater-module/src/main/java/com/alibaba/jvm/sandbox/repeater/module/classloader/PluginClassRouting.java)
`
 @Override
    protected synchronized Class<?> loadClass(String name, boolean resolve) throws ClassNotFoundException {

        // plugin-api的类;slf4j;logback；使用模块加载
        if (userParent(name)) {
            try {
                return super.loadClass(name, resolve);
            } catch (Exception e) {
                // ignore
            }
        }

        // 特殊路由表的；先走特殊路由表；
        if (CollectionUtils.isNotEmpty(routingArray)) {
            for (final Routing routing : routingArray) {
                if (!routing.isHit(name)) {
                    continue;
                }
                final ClassLoader routingClassLoader = routing.classLoader;
                try {
                    return routingClassLoader.loadClass(name);
                } catch (Exception e) {
                    // ignore...
                }
            }
        }

        // 先查一次已加载类的缓存
        final Class<?> loadedClass = findLoadedClass(name);

        if (loadedClass != null) {
            return loadedClass;
        }

        try {
            final Class<?> aClass = findClass(name);
            if (resolve) {
                resolveClass(aClass);
            }
            return aClass;
        } catch (Exception e) {
            return super.loadClass(name, resolve);
        }
    }
`
