### ISSUE TITLE
cleanProtectionDomainWhichCameFromModuleJarClassLoader方法报错，貌似是模块问题？

### ISSUE THREAD

**Issue by hengyoush** [alibaba/jvm-sandbox#419]
2023-04-14 14:47:45 chaosblade WARN  clean ProtectionDomain in ModuleJarClassLoader[crc32=705482150;file=/data/soft/chaos/chaosblade/lib/sandbox/module/sandbox-mgr-module.jar;]'s acc failed.
java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.security.AccessControlContext java.net.URLClassLoader.acc accessible: module java.base does not "opens java.net" to unnamed module @10f1eff9
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
        at com.alibaba.jvm.sandbox.core.util.SandboxReflectUtils.unCaughtGetClassDeclaredJavaFieldValue(SandboxReflectUtils.java:66)
        at com.alibaba.jvm.sandbox.core.classloader.ModuleJarClassLoader.cleanProtectionDomainWhichCameFromModuleJarClassLoader(ModuleJarClassLoader.java:105)
        at com.alibaba.jvm.sandbox.core.classloader.ModuleJarClassLoader.<init>(ModuleJarClassLoader.java:72)
        at com.alibaba.jvm.sandbox.core.classloader.ModuleJarClassLoader.<init>(ModuleJarClassLoader.java:52)
        at com.alibaba.jvm.sandbox.core.manager.impl.ModuleJarLoader.load(ModuleJarLoader.java:121)
        at com.alibaba.jvm.sandbox.core.manager.impl.ModuleLibLoader.load(ModuleLibLoader.java:76)
        at com.alibaba.jvm.sandbox.core.manager.impl.DefaultCoreModuleManager.reset(DefaultCoreModuleManager.java:590)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at com.alibaba.jvm.sandbox.core.util.SandboxProtector.lambda$protectProxy$1(SandboxProtector.java:87)
        at jdk.proxy4/jdk.proxy4.$Proxy29.reset(Unknown Source)
        at com.alibaba.jvm.sandbox.core.server.jetty.JettyCoreServer.bind(JettyCoreServer.java:191)
        at com.alibaba.jvm.sandbox.core.server.ProxyCoreServer.bind(ProxyCoreServer.java:39)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at com.alibaba.jvm.sandbox.agent.AgentLauncher.install(AgentLauncher.java:246)
        at com.alibaba.jvm.sandbox.agent.AgentLauncher.agentmain(AgentLauncher.java:109)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:491)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallAgentmain(InstrumentationImpl.java:513)

环境：
sandbox：1.4.0
jdk版本：17.0.6

**Comment by jvm-rasp** [comment]
这个在jdk17上不支持，有其他方式替代

**Comment by hengyoush** [comment]
> 这个在jdk17上不支持，有其他方式替代

有办法吗 求教

**Comment by oldmanpushcart** [comment]
抱歉，这几天被github的2FA折腾惨了不能登陆上来。我大概知道原因了，我想想办法。

**Comment by oldmanpushcart** [comment]
@hengyoush 这个不会影响到你使用jvm-sandbox，我需要点时间重新评估下这种清理URLClassLoader资源的方法是否还有必要

**Comment by oldmanpushcart** [comment]
我将日志调整为debug，你可以忽略这个错误，我也懒得修福这个问题了。哈哈
