### ISSUE TITLE
启动时报这个错误，但jar包里肯定有这个类的。

### ISSUE THREAD

**Issue by yb755** [alibaba/jvm-sandbox#43]
启动时报这个错误，
java.lang.NoClassDefFoundError: com/alibaba/jvm/sandbox/api/Module
但jar包里肯定有这个类的。并且用  ./sandbox.sh -p xxxx -l 显示模块已加载出来了

2018-01-29 06:55:40 INFO cfg=;port=0;event.pool.enable=true;event.pool.max.total.per.event=2000;event.pool.max.total=6000;provider=/usr/local/sandbox/lib/../provider;sandbox_home=/usr/local/sandbox/lib/..;event.pool.min.idle.per.event=50;event.pool.max.idle.per.event=100;mode=attach;user_module=/.sandbox-module;;namespace=default;ip=0.0.0.0;system_module=/usr/local/sandbox/lib/../module;unsafe.enable=true;cfg=/usr/local/sandbox/lib/../cfg;
2018-01-29 06:55:40 INFO enable event-pool[per-key-idle-min=50;per-key-idle-max=100;per-key-max=2000;total=6000;]
2018-01-29 06:55:40 INFO append ModuleLifeCycleEventListener[listener=com.alibaba.jvm.sandbox.core.manager.impl.DefaultModuleResourceManager@64a26054;].
2018-01-29 06:55:40 INFO loading provider[com.alibaba.jvm.sandbox.provider.api.ModuleJarLoadingChain] was success from provider-jar[/usr/local/sandbox/lib/../provider/sandbox-mgr-provider.jar], impl=com.alibaba.jvm.sandbox.provider.mgr.EmptyModuleJarLoadingChain
2018-01-29 06:55:40 INFO loading provider[com.alibaba.jvm.sandbox.provider.api.ModuleLoadingChain] was success from provider-jar[/usr/local/sandbox/lib/../provider/sandbox-mgr-provider.jar], impl=com.alibaba.jvm.sandbox.provider.mgr.EmptyModuleLoadingChain
2018-01-29 06:55:40 INFO loading provider-jar[/usr/local/sandbox/lib/../provider/sandbox-mgr-provider.jar] was success.
2018-01-29 06:55:40 INFO module loaded found 1 jar in /usr/local/sandbox/lib/../module
2018-01-29 06:55:40 WARN module SPI new instance failed, ignore this SPI.
java.lang.NoClassDefFoundError: com/alibaba/jvm/sandbox/api/Module
at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
at java.lang.ClassLoader.loadClass(ClassLoader.java:412)
at com.alibaba.jvm.sandbox.core.classloader.RoutingURLClassLoader.loadClass(RoutingURLClassLoader.java:69)
at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:274)
at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:363)
at java.util.ServiceLoader$1.next(ServiceLoader.java:445)
at com.alibaba.jvm.sandbox.core.manager.impl.ModuleJarLoader.load(ModuleJarLoader.java:97)
at com.alibaba.jvm.sandbox.core.manager.impl.DefaultCoreModuleManager.reset(DefaultCoreModuleManager.java:507)
at com.alibaba.jvm.sandbox.core.manager.impl.DefaultCoreModuleManager.(DefaultCoreModuleManager.java:87)
at com.alibaba.jvm.sandbox.core.server.jetty.JettyCoreServer.initManager(JettyCoreServer.java:204)
at com.alibaba.jvm.sandbox.core.server.jetty.JettyCoreServer.access$300(JettyCoreServer.java:43)
at com.alibaba.jvm.sandbox.core.server.jetty.JettyCoreServer$2.process(JettyCoreServer.java:222)
at com.alibaba.jvm.sandbox.core.util.Initializer.initProcess(Initializer.java:91)
at com.alibaba.jvm.sandbox.core.server.jetty.JettyCoreServer.bind(JettyCoreServer.java:212)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at com.alibaba.jvm.sandbox.agent.AgentLauncher.main(AgentLauncher.java:221)
at com.alibaba.jvm.sandbox.agent.AgentLauncher.agentmain(AgentLauncher.java:101)
at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:382)
at sun.instrument.InstrumentationImpl.loadClassAndCallAgentmain(InstrumentationImpl.java:407)
Caused by: java.lang.ClassNotFoundException: com.alibaba.jvm.sandbox.api.Module
at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
... 37 common frames omitted
2018-01-29 06:55:41 INFO active module[id=module-mgr;] finish.
2018-01-29 06:55:41 INFO loaded module[id=module-mgr;class=class com.albaba.jvm.sandbox.module.mgr.ModuleMgrModule;] success, loader=ModuleClassLoader[crc32=893661261;file=/usr/local/sandbox/lib/../module/sandbox-mgr-module.jar;]
2018-01-29 06:55:41 INFO active module[id=info;] finish.
2018-01-29 06:55:41 INFO loaded module[id=info;class=class com.albaba.jvm.sandbox.module.mgr.InfoModule;] success, loader=ModuleClassLoader[crc32=893661261;file=/usr/local/sandbox/lib/../module/sandbox-mgr-module.jar;]
2018-01-29 06:55:41 INFO active module[id=control;] finish.
2018-01-29 06:55:41 INFO loaded module[id=control;class=class com.albaba.jvm.sandbox.module.mgr.ControlModule;] success, loader=ModuleClassLoader[crc32=893661261;file=/usr/local/sandbox/lib/../module/sandbox-mgr-module.jar;]
2018-01-29 06:55:41 INFO module loaded found 1 jar in /root/.sandbox-module
2018-01-29 06:55:41 INFO append ModuleLifeCycleEventListener[listener=com.alibaba.jvm.sandbox.core.manager.impl.DefaultModuleEventWatcher@4ceae360;].
2018-01-29 06:55:41 INFO active module[id=broken-clock-tinker;] finish.
2018-01-29 06:55:41 INFO loaded module[id=broken-clock-tinker;class=class com.vbgps.sandbox.BrokenClockTinkerModule;] success, loader=ModuleClassLoader[crc32=2311267895;file=/root/.sandbox-module/sandbox-clock-0.0.1-SNAPSHOT-jar-with-dependencies.jar;]
2018-01-29 06:55:41 INFO jetty-8.0.y.z-SNAPSHOT
2018-01-29 06:55:41 INFO Started SelectChannelConnector@localhost:44628 STARTING
2018-01-29 06:55:41 INFO sandbox start finished.
2018-01-29 06:55:41 INFO server bind to localhost/127.0.0.1:44628 success. cfg=;port=0;event.pool.enable=true;event.pool.max.total.per.event=2000;event.pool.max.total=6000;provider=/usr/local/sandbox/lib/../provider;sandbox_home=/usr/local/sandbox/lib/..;event.pool.min.idle.per.event=50;event.pool.max.idle.per.event=100;mode=attach;user_module=/.sandbox-module;;namespace=default;ip=0.0.0.0;system_module=/usr/local/sandbox/lib/../module;unsafe.enable=true;cfg=/usr/local/sandbox/lib/../cfg;

**Comment by oldmanpushcart** [comment]
pom.xml文件的内容可以给一下么？

**Comment by yb755** [comment]
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.vbgps</groupId>
  <artifactId>sandbox-clock</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  
  <dependencies>
  	
	<dependency>
	    <groupId>com.alibaba.jvm.sandbox</groupId>
	    <artifactId>sandbox-api</artifactId>
	    <version>1.0.9</version>
	</dependency>
	
	
	<dependency>
	    <groupId>javax.servlet</groupId>
	    <artifactId>javax.servlet-api</artifactId>
	    <version>3.0.1</version>
	</dependency>
  </dependencies>
  <build>
    <plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-assembly-plugin</artifactId>
            <executions>
                <execution>
                    <goals>
                        <goal>attached</goal>
                    </goals>
                    <phase>package</phase>
                    <configuration>
                        <descriptorRefs>
                            <descriptorRef>jar-with-dependencies</descriptorRef>
                        </descriptorRefs>
                    </configuration>
                </execution>
            </executions>
        </plugin>
    </plugins>
</build>
</project>

**Comment by yb755** [comment]
<dependency>
	    <groupId>com.alibaba.jvm.sandbox</groupId>
	    <artifactId>sandbox-api</artifactId>
	    <version>1.0.9</version>
	</dependency>
	
	
	<dependency>
	    <groupId>javax.servlet</groupId>
	    <artifactId>javax.servlet-api</artifactId>
	    <version>3.0.1</version>
	</dependency>
  </dependencies>
  <build>
    <plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-assembly-plugin</artifactId>
            <executions>
                <execution>
                    <goals>
                        <goal>attached</goal>
                    </goals>
                    <phase>package</phase>
                    <configuration>
                        <descriptorRefs>
                            <descriptorRef>jar-with-dependencies</descriptorRef>
                        </descriptorRefs>
                    </configuration>
                </execution>
            </executions>
        </plugin>
    </plugins>
</build>
</project>

-->

**Comment by yb755** [comment]
```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.vbgps</groupId>
  <artifactId>sandbox-clock</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  
  <dependencies>
  	<!-- 
	     沙箱模块的API定义二方包
	     这个二方包可以被声明为provided
	-->
	<dependency>
	    <groupId>com.alibaba.jvm.sandbox</groupId>
	    <artifactId>sandbox-api</artifactId>
	    <version>1.0.9</version>
	</dependency>
	
	<!-- 
	     javax.servlet的三方包
	     在沙箱模块中需要用到HttpServletReuqest和HttpServletResponse
	     整个沙箱模块被放置在Servlet容器中完成加载
	-->
	<dependency>
	    <groupId>javax.servlet</groupId>
	    <artifactId>javax.servlet-api</artifactId>
	    <version>3.0.1</version>
	</dependency>
  </dependencies>
  <build>
    <plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-assembly-plugin</artifactId>
            <executions>
                <execution>
                    <goals>
                        <goal>attached</goal>
                    </goals>
                    <phase>package</phase>
                    <configuration>
                        <descriptorRefs>
                            <descriptorRef>jar-with-dependencies</descriptorRef>
                        </descriptorRefs>
                    </configuration>
                </execution>
            </executions>
        </plugin>
    </plugins>
</build>
</project>
```

**Comment by yb755** [comment]
顺便说一下，那个报错，没有影响到Clock例子的运行，例子的两个方法都测试通过了，只是日志中报那个错误

**Comment by oldmanpushcart** [comment]
哦，意思是Clock已经被符合预期的修复了是么？那估计是有一个有问题的module存在了。
```shell
./sandbox.sh -p PID -l
```

看看都有哪些module存在，有可能你之前加载了一个有问题的module但没有卸载

**Comment by oldmanpushcart** [comment]
我也挺奇怪，竟然会找不到这个类...抱歉暂时我没有想到什么足够的信息帮助我判断
