### ISSUE TITLE
请问，我用了1.4.0，为什么还会报module java.base does not "opens java.net" to unnamed module呢

### ISSUE THREAD

**Issue by mxian** [alibaba/jvm-sandbox#467]
本地环境JDK21，直接打包运行1.4.0
但是日志依然报错

com.alibaba.jvm.sandbox.core.util.UnCaughtException: java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.security.AccessControlContext java.net.URLClassLoader.acc accessible: module java.base does not "opens java.net" to unnamed module @7fee8714
	at com.alibaba.jvm.sandbox.core.util.SandboxReflectUtils.unCaughtGetClassDeclaredJavaFieldValue(SandboxReflectUtils.java:70)
	at com.alibaba.jvm.sandbox.core.classloader.ModuleJarClassLoader.cleanProtectionDomainWhichCameFromModuleJarClassLoader(ModuleJarClassLoader.java:105)
	at com.alibaba.jvm.sandbox.core.classloader.ModuleJarClassLoader.<init>(ModuleJarClassLoader.java:72)
	at com.alibaba.jvm.sandbox.core.classloader.ModuleJarClassLoader.<init>(ModuleJarClassLoader.java:52)
	at com.alibaba.jvm.sandbox.core.manager.impl.ModuleJarLoader.load(ModuleJarLoader.java:121)
	at com.alibaba.jvm.sandbox.core.manager.impl.ModuleLibLoader.load(ModuleLibLoader.java:76)
	at com.alibaba.jvm.sandbox.core.manager.impl.DefaultCoreModuleManager.reset(DefaultCoreModuleManager.java:590)

1.4.0不是已经支持高版本JDK了吗？是我哪里配置不对吗？

**Comment by foodjth** [comment]
可以先添加 --add-opens java.base/java.net=ALL-UNNAMED，但是jdk21显然没有支持；

**Comment by mxian** [comment]
> 可以先添加 --add-opens java.base/java.net=ALL-UNNAMED，但是jdk21显然没有支持；

好的。我改了改ASM一些东西，现在已经能支持JDK21了

**Comment by code-bez** [comment]
收到

**Comment by kerchiner** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
