### ISSUE TITLE
docker化部署，第一次编译部署之后，agent方式启动失败，sandbox报异常，但是此时如果直接重启目标应用，又能启动正常

### ISSUE THREAD

**Issue by xiaolangnani** [alibaba/jvm-sandbox#75]
只有在docker第一次编译部署的时候，agent方式会报错
异常如下：
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
2018-04-04 15:22:55 WARN  load sandbox module JAR[file=/home/admin/.sandbox-module/mkagent.jar] failed.
java.io.IOException: 没有那个文件或目录
        at java.io.UnixFileSystem.createFileExclusively(Native Method)
        at java.io.File.createTempFile(File.java:2024)
        at java.io.File.createTempFile(File.java:2070)
        at com.alibaba.jvm.sandbox.core.classloader.ModuleClassLoader.copyToTempFile(ModuleClassLoader.java:39)
        at com.alibaba.jvm.sandbox.core.classloader.ModuleClassLoader.<init>(ModuleClassLoader.java:47)
        at com.alibaba.jvm.sandbox.core.manager.impl.ModuleJarLoader.load(ModuleJarLoader.java:89)
        at com.alibaba.jvm.sandbox.core.manager.impl.DefaultCoreModuleManager.reset(DefaultCoreModuleManager.java:509)
        at com.alibaba.jvm.sandbox.core.manager.impl.DefaultCoreModuleManager.<init>(DefaultCoreModuleManager.java:87)
        at com.alibaba.jvm.sandbox.core.server.jetty.JettyCoreServer.initManager(JettyCoreServer.java:206)
        at com.alibaba.jvm.sandbox.core.server.jetty.JettyCoreServer.access$400(JettyCoreServer.java:38)
        at com.alibaba.jvm.sandbox.core.server.jetty.JettyCoreServer$2.process(JettyCoreServer.java:222)
        at com.alibaba.jvm.sandbox.core.util.Initializer.initProcess(Initializer.java:91)
        at com.alibaba.jvm.sandbox.core.server.jetty.JettyCoreServer.bind(JettyCoreServer.java:216)
        at com.alibaba.jvm.sandbox.core.server.ProxyCoreServer.bind(ProxyCoreServer.java:39)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

**Comment by zhaoyb1990** [comment]
遇到过同样的问题，原因是sandbox在agent启动的时候 -Djava.io.tmpdir未创建，可以通过docker手动创建规避问题

**Comment by jackychee** [comment]
@oldmanpushcart  夏驰兄，确认下这样优化是否可以。
