### ISSUE TITLE
 Agent JAR loaded but agent failed to initialize

### ISSUE THREAD

**Issue by woshihoujinxin** [alibaba/jvm-sandbox#97]
$ ./sandbox.sh -p 17116
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.alibaba.jvm.sandbox.core.CoreLauncher.attachAgent(CoreLauncher.java:79)
        at com.alibaba.jvm.sandbox.core.CoreLauncher.<init>(CoreLauncher.java:20)
        at com.alibaba.jvm.sandbox.core.CoreLauncher.main(CoreLauncher.java:44)
Caused by: com.sun.tools.attach.AgentInitializationException: Agent JAR loaded but agent failed to initialize
        at sun.tools.attach.HotSpotVirtualMachine.loadAgent(HotSpotVirtualMachine.java:121)
        ... 7 more
sandbox load jvm failed : Agent JAR loaded but agent failed to initialize
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
attach JVM 17116 fail.

在windows下用git bash执行会报以下异常不知如何处理？

**Comment by oldmanpushcart** [comment]
看下应用的主日志中出什么错

**Comment by qiujing2019** [comment]
我也碰到这个问题了。怎么解决的？

**Comment by JangNum** [comment]
重启应用就可以了

**Comment by biaohanli** [comment]
> 重启应用就可以了

不行，这个问题还是每次都会出现，重启也没有用
